import {StyleSheet} from 'react-native';
import {type AppColors} from '../../../theme';

export const createStyles = (colors: AppColors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 40,
  },
  main: {
    width: '100%',
    maxWidth: 560,
    alignSelf: 'center',
    paddingHorizontal: 20,
    gap: 14,
  },
  pageHeader: {
    marginTop: 8,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  backBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.actionBlue,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  titleBlock: {
    flex: 1,
    gap: 2,
  },
  pageTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.textDark,
    letterSpacing: -0.5,
    lineHeight: 28,
  },
  pageSubtitle: {
    fontSize: 12,
    fontWeight: '400',
    color: colors.textSoft,
    lineHeight: 16,
  },
  profileCard: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    borderWidth: 0.75,
    borderColor: colors.borderSoft,
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 14,
    gap: 16,
  },
  profileTop: {
    alignItems: 'center',
    gap: 4,
  },
  avatarWrap: {
    width: 72,
    height: 72,
    borderRadius: 18,
    borderWidth: 2,
    borderColor: colors.actionTint28,
    overflow: 'hidden',
    marginBottom: 6,
    backgroundColor: colors.track,
  },
  avatarImage: {
    width: '100%',
    height: '100%',
  },
  profileName: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textDark,
    textAlign: 'center',
  },
  profileRole: {
    fontSize: 12,
    fontWeight: '400',
    color: colors.textSoft,
    textAlign: 'center',
    marginTop: 2,
  },
  matchBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginTop: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: colors.actionTint1,
  },
  matchText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.actionBlue,
  },
  detailsList: {
    gap: 10,
  },
  detailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  detailText: {
    fontSize: 12,
    fontWeight: '400',
    color: colors.textSecondary,
    flex: 1,
  },
  actionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingTop: 4,
    borderTopWidth: 0.75,
    borderTopColor: colors.borderSoft,
  },
  outlineBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    height: 36,
    borderRadius: 12,
    borderWidth: 0.75,
    borderColor: colors.borderSoft,
    backgroundColor: colors.track,
  },
  outlineBtnText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textDark,
  },
  decisionCard: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    borderWidth: 0.75,
    borderColor: colors.borderSoft,
    padding: 18,
    gap: 10,
  },
  sectionLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: colors.textSoft,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  decisionList: {
    gap: 8,
  },
  primaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    height: 40,
    borderRadius: 12,
    backgroundColor: colors.actionBlue,
  },
  primaryBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.white,
  },
  secondaryBtn: {
    height: 40,
    borderRadius: 12,
    backgroundColor: colors.surface,
    borderWidth: 0.75,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textDark,
  },
  rejectBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    height: 40,
    borderRadius: 12,
    backgroundColor: colors.surface,
    borderWidth: 0.75,
    borderColor: colors.border,
  },
  rejectBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.absent,
  },
  tabsWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  tab: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: colors.track,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  tabActive: {
    backgroundColor: colors.actionTint1,
    borderColor: colors.actionBlue,
  },
  tabLabel: {
    fontSize: 11,
    fontWeight: '500',
    color: colors.textSoft,
    textAlign: 'center',
  },
  tabLabelActive: {
    color: colors.actionBlue,
    fontWeight: '600',
  },
  panel: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    borderWidth: 0.75,
    borderColor: colors.borderSoft,
    padding: 18,
    gap: 14,
  },
  summaryHeader: {
    gap: 4,
  },
  aboutTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textDark,
  },
  aboutText: {
    fontSize: 12,
    fontWeight: '400',
    color: colors.textSecondary,
    lineHeight: 18,
  },
  skillsList: {
    gap: 14,
    marginTop: 2,
  },
  skillRow: {
    gap: 6,
  },
  skillHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  skillLabel: {
    fontSize: 11,
    fontWeight: '500',
    color: colors.textDark,
  },
  skillPercent: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.actionBlue,
  },
  skillTrack: {
    height: 6,
    borderRadius: 999,
    backgroundColor: colors.track,
    overflow: 'hidden',
  },
  skillFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: colors.actionBlue,
  },
  resumeHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  downloadOutlineBtn: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: colors.actionTint1,
    borderWidth: 1,
    borderColor: colors.actionBlue,
  },
  downloadOutlineBtnText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.actionBlue,
  },
  resumePreviewBox: {
    borderRadius: 16,
    backgroundColor: colors.track,
    paddingHorizontal: 16,
    paddingVertical: 14,
    gap: 4,
  },
  resumeRole: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textDark,
  },
  resumeMeta: {
    fontSize: 10,
    fontWeight: '600',
    color: colors.textSoft,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  panelTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textDark,
  },
  screeningList: {
    gap: 10,
  },
  qaBlock: {
    gap: 6,
    borderRadius: 16,
    backgroundColor: colors.track,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  qaQuestion: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textDark,
  },
  qaAnswer: {
    fontSize: 10,
    fontWeight: '600',
    color: colors.textSoft,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    lineHeight: 15,
  },
  scoreList: {
    gap: 10,
  },
  scoreRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    borderRadius: 16,
    backgroundColor: colors.track,
    paddingHorizontal: 16,
    paddingVertical: 16,
  },
  scoreLabel: {
    flex: 1,
    fontSize: 14,
    fontWeight: '700',
    color: colors.textDark,
  },
  stars: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  starBtn: {
    padding: 1,
  },
});
