import {StyleSheet} from 'react-native';
import {type AppColors} from '../../../theme';

export const createStyles = (colors: AppColors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 110,
    gap: 14,
  },
  main: {
    paddingHorizontal: 20,
    gap: 14,
  },
  tabsScroll: {
    flexGrow: 0,
  },
  tabsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 2,
    paddingLeft: 20,
    paddingRight: 28,
  },
  tab: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    height: 28,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: colors.surface,
    borderWidth: 0.75,
    borderColor: colors.borderSoft,
    flexShrink: 0,
  },
  tabActive: {
    backgroundColor: colors.actionBlue,
    borderColor: colors.actionBlue,
  },
  tabLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  tabLabelActive: {
    color: colors.white,
  },
  pageHeader: {
    gap: 10,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    minWidth: 0,
  },
  backBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.actionBlue,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    marginTop: 4,
  },
  titleBlock: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  pageTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.textDark,
    letterSpacing: -0.4,
  },
  pageSubtitle: {
    fontSize: 12,
    fontWeight: '400',
    color: colors.textSoft,
    lineHeight: 17,
  },
  exportRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  exportBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    height: 32,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: colors.surface,
    borderWidth: 0.75,
    borderColor: colors.border,
  },
  exportBtnText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textDark,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 28,
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 8,
    gap: 14,
    shadowColor: '#0B152C',
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.08,
    shadowRadius: 18,
    elevation: 3,
  },
  search: {
    height: 44,
    borderRadius: 999,
    backgroundColor: '#F1F4F8',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    gap: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 13,
    fontWeight: '400',
    color: colors.textDark,
    padding: 0,
  },
  filterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  showingText: {
    flexShrink: 1,
    fontSize: 11,
    fontWeight: '400',
    color: colors.textSoft,
  },
  filterActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  filterBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    height: 28,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: '#E5EAF0',
  },
  filterBtnText: {
    fontSize: 11,
    fontWeight: '500',
    color: colors.textDark,
  },
  table: {
    width: '100%',
  },
  tableHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 4,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#EEF1F5',
  },
  tableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 46,
    paddingVertical: 11,
    borderBottomWidth: 1,
    borderBottomColor: '#F3F5F8',
  },
  tableRowLast: {
    borderBottomWidth: 0,
  },
  colOrder: {
    flex: 1.1,
    paddingRight: 4,
  },
  colCustomer: {
    flex: 1.7,
    paddingRight: 6,
  },
  colAmount: {
    flex: 1,
    paddingRight: 4,
  },
  colPayment: {
    flex: 1.2,
    paddingRight: 4,
    alignItems: 'flex-start',
  },
  colStatus: {
    flex: 1.3,
    alignItems: 'flex-start',
  },
  headerText: {
    fontSize: 9,
    fontWeight: '700',
    color: '#8A94A6',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  orderId: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.actionBlue,
  },
  customer: {
    fontSize: 12,
    fontWeight: '500',
    color: colors.textDark,
  },
  amount: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textDark,
  },
  badge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    alignSelf: 'flex-start',
  },
  badgeText: {
    fontSize: 10,
    fontWeight: '600',
  },
  comingSoonWrap: {
    minHeight: 220,
    borderRadius: 24,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 24,
    shadowColor: '#0B152C',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 2,
  },
  comingSoonText: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.textSoft,
  },
  sendRemindersBtn: {
    height: 32,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: colors.actionBlue,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'flex-end',
  },
  sendRemindersText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.white,
  },
  lateListCard: {
    backgroundColor: colors.surface,
    borderRadius: 28,
    padding: 14,
    gap: 12,
    shadowColor: '#0B152C',
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.08,
    shadowRadius: 18,
    elevation: 3,
  },
  lateItem: {
    backgroundColor: '#FFF5F5',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#F5D0D5',
    padding: 14,
    gap: 12,
  },
  lateTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  lateWarnIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#FFE4E8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  lateInfo: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  lateName: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textDark,
  },
  lateMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
  },
  lateOrderId: {
    fontSize: 12,
    fontWeight: '700',
    color: '#E11D48',
  },
  lateVehicle: {
    fontSize: 12,
    fontWeight: '400',
    color: colors.textSoft,
  },
  latePills: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
  },
  latePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    height: 28,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: colors.surface,
    borderWidth: 0.75,
    borderColor: '#F0E4E6',
  },
  latePillTime: {
    fontSize: 11,
    fontWeight: '700',
    color: '#E11D48',
  },
  latePillMuted: {
    fontSize: 11,
    fontWeight: '500',
    color: colors.textSoft,
  },
  latePillFee: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.textDark,
  },
  lateActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: 8,
  },
  lateOutlineBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    height: 30,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: colors.surface,
    borderWidth: 0.75,
    borderColor: colors.border,
  },
  lateOutlineBtnText: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.textDark,
  },
  latePrimaryBtn: {
    height: 30,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: colors.actionBlue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  latePrimaryBtnText: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.white,
  },
  invoiceActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: 6,
  },
  invoiceOutlineBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    height: 32,
    paddingHorizontal: 11,
    borderRadius: 999,
    backgroundColor: colors.surface,
    borderWidth: 0.75,
    borderColor: colors.border,
  },
  invoiceOutlineBtnText: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.textDark,
  },
  createInvoiceBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    height: 32,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: colors.actionBlue,
  },
  createInvoiceBtnText: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.white,
  },
  metricsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  ledgerCard: {
    backgroundColor: colors.surface,
    borderRadius: 28,
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 8,
    gap: 14,
    shadowColor: '#0B152C',
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.08,
    shadowRadius: 18,
    elevation: 3,
  },
  colInvoice: {
    flex: 1.15,
    paddingRight: 4,
  },
  colInvCustomer: {
    flex: 1.55,
    paddingRight: 4,
  },
  colInvAmount: {
    flex: 0.95,
    paddingRight: 4,
  },
  colDue: {
    flex: 0.9,
    paddingRight: 4,
  },
  colInvStatus: {
    flex: 1.15,
    paddingRight: 2,
    alignItems: 'flex-start',
  },
  colView: {
    width: 22,
    alignItems: 'flex-end',
  },
  dueText: {
    fontSize: 11,
    fontWeight: '500',
    color: colors.textSoft,
  },
  viewBtn: {
    width: 22,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  historyWrap: {
    gap: 14,
  },
  historyCard: {
    backgroundColor: colors.surface,
    borderRadius: 24,
    borderWidth: 0.75,
    borderColor: colors.borderSoft,
    padding: 18,
    gap: 8,
    shadowColor: '#0B152C',
    shadowOffset: {width: 0, height: 6},
    shadowOpacity: 0.06,
    shadowRadius: 14,
    elevation: 2,
  },
  historyEyebrow: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.textSoft,
    letterSpacing: 0.6,
  },
  historyCardTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textDark,
    marginBottom: 6,
  },
  historyTableHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 6,
    paddingBottom: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  historyTableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.borderSoft,
  },
  historyTableRowLast: {
    borderBottomWidth: 0,
  },
  historyHeaderText: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.textSoft,
    letterSpacing: 0.4,
  },
  historyColVehicle: {
    flex: 1.6,
    paddingRight: 8,
  },
  historyColDays: {
    width: 48,
    textAlign: 'center',
  },
  historyColAmount: {
    width: 72,
    textAlign: 'right',
  },
  historyVehicle: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textDark,
  },
  historyDays: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textSecondary,
    textAlign: 'center',
  },
  historyAmount: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textDark,
    textAlign: 'right',
  },
  historyEmpty: {
    paddingVertical: 16,
    fontSize: 12,
    color: colors.textSoft,
  },
});
