import {StyleSheet} from 'react-native';
import {type AppColors} from '../../../theme';

export const createStyles = (c: AppColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: c.background,
    },
    scroll: {
      flex: 1,
    },
    scrollContent: {
      flexGrow: 1,
      paddingBottom: 28,
      gap: 14,
    },
    header: {
      paddingHorizontal: 20,
      paddingTop: 16,
      gap: 4,
    },
    title: {
      fontSize: 22,
      fontWeight: '700',
      color: c.textDark,
    },
    subtitle: {
      fontSize: 13,
      color: c.textSoft,
      lineHeight: 18,
    },
    searchWrap: {
      marginHorizontal: 20,
      marginTop: 8,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      backgroundColor: c.surface,
      borderRadius: 14,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
      paddingHorizontal: 14,
      minHeight: 46,
    },
    searchInput: {
      flex: 1,
      fontSize: 14,
      color: c.text,
      paddingVertical: 10,
    },
    filtersRow: {
      paddingHorizontal: 20,
      gap: 8,
    },
    chip: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: c.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
      marginRight: 8,
    },
    chipActive: {
      backgroundColor: c.actionTint12,
      borderColor: c.actionBlue,
    },
    chipText: {
      fontSize: 12,
      fontWeight: '600',
      color: c.textSecondary,
    },
    chipTextActive: {
      color: c.actionBlue,
    },
    card: {
      marginHorizontal: 20,
      backgroundColor: c.surface,
      borderRadius: 16,
      padding: 16,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
      gap: 8,
      shadowColor: '#0B152C',
      shadowOffset: {width: 0, height: 8},
      shadowOpacity: 0.06,
      shadowRadius: 12,
      elevation: 2,
    },
    cardTop: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 10,
    },
    jobTitle: {
      flex: 1,
      fontSize: 16,
      fontWeight: '700',
      color: c.textDark,
    },
    typeBadge: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 8,
      backgroundColor: c.actionTint12,
    },
    typeBadgeText: {
      fontSize: 11,
      fontWeight: '600',
      color: c.actionBlue,
    },
    meta: {
      fontSize: 13,
      color: c.textSecondary,
    },
    detailsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
      marginTop: 2,
    },
    detailItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    detailText: {
      fontSize: 12,
      color: c.textSoft,
    },
    salary: {
      fontSize: 13,
      fontWeight: '700',
      color: c.textDark,
      marginTop: 2,
    },
    emptyWrap: {
      paddingHorizontal: 28,
      paddingTop: 40,
      alignItems: 'center',
      gap: 8,
    },
    emptyTitle: {
      fontSize: 15,
      fontWeight: '700',
      color: c.textDark,
    },
    emptyText: {
      fontSize: 13,
      lineHeight: 19,
      color: c.textSoft,
      textAlign: 'center',
    },
    loader: {
      paddingTop: 48,
    },
    // Detail
    backBtn: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: c.actionBlue,
      alignItems: 'center',
      justifyContent: 'center',
    },
    detailHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingHorizontal: 20,
      paddingTop: 16,
    },
    detailTitle: {
      flex: 1,
      fontSize: 18,
      fontWeight: '700',
      color: c.textDark,
    },
    sectionCard: {
      marginHorizontal: 20,
      backgroundColor: c.surface,
      borderRadius: 16,
      padding: 16,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
      gap: 8,
    },
    sectionLabel: {
      fontSize: 13,
      fontWeight: '700',
      color: c.textDark,
    },
    sectionBody: {
      fontSize: 13,
      lineHeight: 20,
      color: c.textSecondary,
    },
    applyBar: {
      paddingHorizontal: 20,
      paddingTop: 10,
      paddingBottom: 16,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: c.border,
      backgroundColor: c.surface,
    },
    applyBtn: {
      minHeight: 48,
      borderRadius: 14,
      backgroundColor: c.actionBlue,
      alignItems: 'center',
      justifyContent: 'center',
    },
    applyBtnText: {
      color: c.white,
      fontSize: 15,
      fontWeight: '700',
    },
    applyBtnDisabled: {
      opacity: 0.6,
    },
    modalBackdrop: {
      flex: 1,
      backgroundColor: 'rgba(11,21,44,0.45)',
      justifyContent: 'flex-end',
    },
    modalSheet: {
      backgroundColor: c.surface,
      borderTopLeftRadius: 20,
      borderTopRightRadius: 20,
      paddingHorizontal: 20,
      paddingTop: 16,
      paddingBottom: 24,
      gap: 10,
      maxHeight: '88%',
    },
    modalTitle: {
      fontSize: 17,
      fontWeight: '700',
      color: c.textDark,
    },
    modalHint: {
      fontSize: 12,
      color: c.textSoft,
      marginBottom: 4,
    },
    fieldLabel: {
      fontSize: 12,
      fontWeight: '600',
      color: c.textSecondary,
      marginTop: 4,
    },
    fieldInput: {
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
      borderRadius: 12,
      paddingHorizontal: 12,
      paddingVertical: 10,
      fontSize: 14,
      color: c.text,
      backgroundColor: c.background,
    },
    fieldArea: {
      minHeight: 90,
      textAlignVertical: 'top',
    },
    modalActions: {
      flexDirection: 'row',
      gap: 10,
      marginTop: 8,
    },
    modalSecondary: {
      flex: 1,
      minHeight: 46,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: c.background,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
    },
    modalSecondaryText: {
      fontSize: 14,
      fontWeight: '600',
      color: c.textSecondary,
    },
    modalPrimary: {
      flex: 1,
      minHeight: 46,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: c.actionBlue,
    },
    modalPrimaryText: {
      fontSize: 14,
      fontWeight: '700',
      color: c.white,
    },
  });
