import {StyleSheet} from 'react-native';
import {type AppColors} from '../../../theme';

export const createStyles = (colors: AppColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    loading: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    scroll: {flex: 1},
    scrollContent: {
      paddingBottom: 40,
      gap: 14,
    },
    main: {
      paddingHorizontal: 20,
      gap: 14,
    },
    pageHeader: {gap: 10},
    titleRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
    },
    backBtn: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: colors.actionBlue,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 2,
    },
    titleCopy: {
      flex: 1,
      minWidth: 0,
      gap: 3,
    },
    menuBtn: {
      width: 28,
      height: 28,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 2,
    },
    pageTitle: {
      fontSize: 22,
      fontWeight: '700',
      color: colors.textDark,
      letterSpacing: -0.5,
    },
    pageSubtitle: {
      fontSize: 12,
      color: colors.textSoft,
      lineHeight: 17,
    },
    actions: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: 8,
    },
    secondaryBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      height: 36,
      paddingHorizontal: 14,
      borderRadius: 18,
      borderWidth: 0.75,
      borderColor: colors.border,
      backgroundColor: colors.surface,
    },
    secondaryBtnText: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.textDark,
    },
    primaryBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      height: 36,
      paddingHorizontal: 14,
      borderRadius: 18,
      backgroundColor: colors.actionBlue,
    },
    primaryBtnText: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.white,
    },
    metricsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      rowGap: 12,
    },
    listCard: {
      backgroundColor: colors.surface,
      borderRadius: 24,
      borderWidth: 0.75,
      borderColor: colors.borderSoft,
      padding: 16,
      gap: 14,
      shadowColor: '#0B152C',
      shadowOffset: {width: 0, height: 6},
      shadowOpacity: 0.06,
      shadowRadius: 12,
      elevation: 2,
    },
    sectionEyebrow: {
      fontSize: 10,
      fontWeight: '700',
      color: colors.textSoft,
      letterSpacing: 0.8,
      textTransform: 'uppercase',
    },
    sectionTitle: {
      fontSize: 17,
      fontWeight: '700',
      color: colors.textDark,
      letterSpacing: -0.3,
    },
    sectionHeader: {gap: 2},
    invoiceCard: {
      borderRadius: 18,
      borderWidth: 0.75,
      borderColor: colors.borderSoft,
      backgroundColor: colors.surface,
      padding: 14,
      gap: 12,
      shadowColor: '#0B152C',
      shadowOffset: {width: 0, height: 3},
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 1,
    },
    invoiceGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      rowGap: 10,
    },
    invoiceCell: {
      width: '50%',
      gap: 2,
      paddingRight: 8,
    },
    cellLabel: {
      fontSize: 9,
      fontWeight: '700',
      color: colors.textSoft,
      letterSpacing: 0.4,
      textTransform: 'uppercase',
    },
    cellValue: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.textDark,
    },
    cellLink: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.actionBlue,
    },
    invoiceActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.borderSoft,
      paddingTop: 10,
    },
    actionIconBtn: {
      width: 32,
      height: 32,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.track,
    },
    emptyText: {
      fontSize: 13,
      color: colors.textSoft,
      textAlign: 'center',
      paddingVertical: 20,
    },
    listGap: {gap: 10},
  });
