import {StyleSheet} from 'react-native';
import {type AppColors} from '../../../theme';

export const createStyles = (colors: AppColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    scroll: {
      flex: 1,
    },
    scrollContent: {
      paddingBottom: 48,
    },
    main: {
      paddingHorizontal: 20,
      gap: 14,
      paddingTop: 8,
    },
    pageHeader: {
      gap: 10,
    },
    titleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    backBtn: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: colors.actionBlue,
      alignItems: 'center',
      justifyContent: 'center',
    },
    titleCopy: {
      flex: 1,
      minWidth: 0,
      gap: 3,
    },
    pageTitle: {
      fontSize: 20,
      fontWeight: '600',
      color: colors.textDark,
      letterSpacing: -0.6,
    },
    pageSubtitle: {
      fontSize: 10.5,
      color: colors.textSoft,
      marginTop: 3,
      lineHeight: 16,
    },
    card: {
      backgroundColor: colors.surface,
      borderRadius: 24,
      borderWidth: 0.75,
      borderColor: colors.borderSoft,
      padding: 16,
      gap: 14,
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 3},
      shadowOpacity: 0.08,
      shadowRadius: 6,
      elevation: 2,
    },
    formPanel: {
      backgroundColor: 'rgba(237,242,248,0.35)',
      borderRadius: 21,
      borderWidth: 0.75,
      borderColor: colors.borderSoft,
      paddingHorizontal: 16,
      paddingTop: 20,
      paddingBottom: 16,
      gap: 14,
    },
    stepEyebrow: {
      fontSize: 9,
      fontWeight: '700',
      color: colors.actionBlue,
      letterSpacing: 0.5,
      textTransform: 'uppercase',
    },
    stepTitle: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.textDark,
      letterSpacing: -0.3,
    },
    stepDescription: {
      fontSize: 10.5,
      color: colors.textSoft,
      lineHeight: 16,
    },
    fieldsStack: {
      gap: 12,
      width: '100%',
    },
    uploadArea: {
      minHeight: 88,
      borderRadius: 16,
      borderWidth: 1.2,
      borderStyle: 'dashed',
      borderColor: colors.actionBlue,
      backgroundColor: colors.actionTint06,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 16,
      paddingVertical: 14,
      gap: 6,
    },
    uploadTitle: {
      fontSize: 10.5,
      fontWeight: '600',
      color: colors.textDark,
      textAlign: 'center',
    },
    uploadHint: {
      fontSize: 8.5,
      color: colors.textSoft,
      textAlign: 'center',
      lineHeight: 13,
    },
    uploadRow: {
      flexDirection: 'row',
      gap: 10,
    },
    uploadHalf: {
      flex: 1,
      minHeight: 100,
    },
    tagRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
    },
    tag: {
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 999,
      backgroundColor: colors.searchBg,
      borderWidth: 0.75,
      borderColor: colors.borderSoft,
    },
    tagText: {
      fontSize: 8.5,
      fontWeight: '500',
      color: colors.textSoft,
    },
    infoBox: {
      borderRadius: 14,
      borderWidth: 0.75,
      borderColor: 'rgba(59,130,246,0.2)',
      backgroundColor: 'rgba(59,130,246,0.08)',
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    infoText: {
      fontSize: 9.5,
      color: colors.actionBlue,
      lineHeight: 14,
    },
    reviewGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    reviewCell: {
      width: '47%',
      backgroundColor: colors.searchBg,
      borderRadius: 14,
      paddingHorizontal: 12,
      paddingVertical: 10,
      gap: 4,
    },
    reviewLabel: {
      fontSize: 8,
      fontWeight: '700',
      color: colors.textSoft,
      letterSpacing: 0.4,
    },
    reviewValue: {
      fontSize: 11,
      fontWeight: '700',
      color: colors.textDark,
    },
    readyBox: {
      borderRadius: 16,
      borderWidth: 0.75,
      borderColor: 'rgba(32,180,107,0.3)',
      backgroundColor: colors.badgeActiveBg,
      paddingHorizontal: 14,
      paddingVertical: 12,
      gap: 4,
    },
    readyTitle: {
      fontSize: 11,
      fontWeight: '700',
      color: colors.successBright,
    },
    readyText: {
      fontSize: 9.5,
      color: colors.textSoft,
      lineHeight: 14,
    },
    footer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      paddingTop: 4,
    },
    prevBtn: {
      height: 30,
      borderRadius: 18,
      borderWidth: 0.75,
      borderColor: colors.border,
      backgroundColor: '#F7FBFD',
      paddingHorizontal: 14,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    prevBtnDisabled: {
      opacity: 0.45,
    },
    prevBtnText: {
      fontSize: 10.5,
      fontWeight: '500',
      color: colors.textDark,
    },
    nextBtn: {
      height: 30,
      borderRadius: 18,
      backgroundColor: colors.actionBlue,
      paddingHorizontal: 14,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    nextBtnText: {
      fontSize: 10.5,
      fontWeight: '600',
      color: colors.white,
    },
  });
