import {StyleSheet} from 'react-native';
import {type AppColors} from '../../../theme';

export const createStyles = (colors: AppColors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 40,
    gap: 14,
  },
  main: {
    width: '100%',
    maxWidth: 560,
    alignSelf: 'center',
    paddingHorizontal: 20,
    gap: 14,
  },
  pageHeader: {
    marginTop: 8,
    gap: 10,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  backBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.actionBlue,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  titleBlock: {
    flex: 1,
    gap: 2,
  },
  eyebrow: {
    fontSize: 9,
    fontWeight: '600',
    color: colors.textSoft,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  pageTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.textDark,
    letterSpacing: -0.3,
    lineHeight: 20,
  },
  recordingRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  recordingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: colors.badgeOverdueBg,
  },
  recordingDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.error,
  },
  recordingText: {
    fontSize: 10,
    fontWeight: '600',
    color: colors.error,
  },
  videoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  callCard: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    borderWidth: 0.75,
    borderColor: colors.borderSoft,
    paddingTop: 10,
    paddingHorizontal: 10,
    paddingBottom: 10,
    shadowColor: '#0B152C',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 2,
  },
  videoTile: {
    width: '48.2%',
    flexGrow: 1,
    aspectRatio: 1.05,
    borderRadius: 14,
    overflow: 'hidden',
    justifyContent: 'flex-end',
    padding: 10,
  },
  videoTileActive: {
    borderWidth: 2.5,
    borderColor: colors.actionBlue,
  },
  videoInitials: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoInitialsText: {
    fontSize: 28,
    fontWeight: '700',
    color: 'rgba(255,255,255,0.85)',
  },
  videoOverlay: {
    gap: 1,
    zIndex: 2,
  },
  videoName: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.white,
  },
  videoRole: {
    fontSize: 10,
    fontWeight: '500',
    color: 'rgba(255,255,255,0.85)',
  },
  micBadge: {
    position: 'absolute',
    right: 8,
    bottom: 8,
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: colors.actionBlue,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 3,
  },
  youBadge: {
    position: 'absolute',
    right: 8,
    bottom: 8,
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 999,
    backgroundColor: 'rgba(0,0,0,0.55)',
    zIndex: 3,
  },
  youBadgeText: {
    fontSize: 9,
    fontWeight: '600',
    color: colors.white,
  },
  controlsBar: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
    gap: 8,
  },
  controlsGroup: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    minWidth: 0,
  },
  controlBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: colors.track,
    alignItems: 'center',
    justifyContent: 'center',
  },
  endCallBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    flexShrink: 0,
    gap: 5,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#E53935',
    paddingHorizontal: 10,
  },
  endCallText: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.white,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    borderWidth: 0.75,
    borderColor: colors.borderSoft,
    padding: 16,
    gap: 14,
    shadowColor: '#0B152C',
    shadowOffset: {width: 0, height: 3},
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 1,
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cardEyebrow: {
    fontSize: 9,
    fontWeight: '600',
    color: colors.textSoft,
    letterSpacing: 0.9,
    textTransform: 'uppercase',
  },
  scoreRows: {
    gap: 12,
  },
  scoreRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  scoreLabel: {
    flex: 1,
    fontSize: 13,
    fontWeight: '500',
    color: colors.textDark,
  },
  stars: {
    flexDirection: 'row',
    gap: 4,
  },
  starBtn: {
    padding: 1,
  },
  notesInput: {
    minHeight: 56,
    borderRadius: 14,
    borderWidth: 0.75,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 12,
    color: colors.textDark,
    textAlignVertical: 'top',
  },
  chatList: {
    gap: 8,
  },
  chatBubble: {
    alignSelf: 'flex-start',
    maxWidth: '88%',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: colors.track,
  },
  chatBubbleYou: {
    alignSelf: 'flex-start',
    backgroundColor: colors.actionTint12,
  },
  chatText: {
    fontSize: 12,
    fontWeight: '400',
    color: colors.textDark,
    lineHeight: 17,
  },
  chatSender: {
    fontWeight: '700',
  },
  chatInputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    height: 42,
    borderRadius: 21,
    borderWidth: 0.75,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingLeft: 14,
    paddingRight: 6,
    gap: 8,
  },
  chatInput: {
    flex: 1,
    fontSize: 12,
    color: colors.textDark,
    paddingVertical: 0,
  },
  sendBtn: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: colors.actionBlue,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
