import {StyleSheet} from 'react-native';
import {type AppColors} from '../../../theme';

export const createStyles = (colors: AppColors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 40,
    gap: 14,
  },
  main: {
    width: '100%',
    maxWidth: 560,
    alignSelf: 'center',
    paddingHorizontal: 20,
    gap: 14,
  },
  heroCard: {
    marginTop: 8,
    backgroundColor: colors.surface,
    borderRadius: 20,
    borderWidth: 0.75,
    borderColor: colors.borderSoft,
    padding: 16,
    gap: 16,
    shadowColor: '#0B152C',
    shadowOffset: {width: 0, height: 3},
    shadowOpacity: 0.06,
    shadowRadius: 10,
    elevation: 2,
  },
  heroTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.actionBlue,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  heroCopy: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  heroTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.textDark,
    letterSpacing: -0.4,
  },
  heroSubtitle: {
    fontSize: 12,
    fontWeight: '400',
    color: colors.textSoft,
    lineHeight: 17,
  },
  badgesRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 6,
  },
  usersBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    backgroundColor: colors.actionTint1,
  },
  usersBadgeText: {
    fontSize: 9,
    fontWeight: '600',
    color: colors.actionBlue,
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
    backgroundColor: colors.track,
  },
  statusBadgeText: {
    fontSize: 9,
    fontWeight: '600',
    color: colors.textDark,
  },
  actionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 8,
  },
  outlineBtn: {
    height: 32,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 0.75,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  outlineBtnText: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.textDark,
  },
  deleteBtnText: {
    color: colors.error,
  },
  primaryBtn: {
    height: 32,
    paddingHorizontal: 12,
    borderRadius: 999,
    backgroundColor: colors.actionBlue,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  primaryBtnText: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.white,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    borderWidth: 0.75,
    borderColor: colors.borderSoft,
    padding: 16,
    gap: 12,
    shadowColor: '#0B152C',
    shadowOffset: {width: 0, height: 3},
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 1,
  },
  statLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: colors.textSoft,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  statValue: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.textDark,
  },
  statFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  statFooterText: {
    fontSize: 12,
    fontWeight: '400',
    color: colors.textSoft,
  },
  sectionEyebrow: {
    fontSize: 10,
    fontWeight: '600',
    color: colors.textSoft,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textDark,
  },
  sectionHeader: {
    gap: 2,
  },
  membersHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  assignLink: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.actionBlue,
    marginTop: 2,
  },
  matrixScroll: {
    marginHorizontal: -4,
  },
  matrix: {
    minWidth: 520,
  },
  matrixHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingBottom: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  matrixRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.borderSoft,
  },
  matrixModuleCol: {
    width: 88,
    paddingRight: 6,
  },
  matrixModuleHeader: {
    fontSize: 9,
    fontWeight: '700',
    color: colors.textSoft,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  matrixModuleLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textDark,
  },
  matrixRoleCol: {
    width: 78,
    alignItems: 'center',
    justifyContent: 'center',
  },
  matrixRoleHeader: {
    fontSize: 8,
    fontWeight: '700',
    color: colors.textSoft,
    letterSpacing: 0.3,
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  grantYes: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: 'rgba(32,180,107,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  grantYesText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.successBright,
  },
  grantNo: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: colors.track,
    alignItems: 'center',
    justifyContent: 'center',
  },
  grantNoText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.textSoft,
  },
  memberList: {
    gap: 0,
  },
  memberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.borderSoft,
  },
  memberRowLast: {
    borderBottomWidth: 0,
    paddingBottom: 0,
  },
  memberAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  memberAvatarText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.white,
  },
  memberInfo: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  memberName: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textDark,
  },
  memberEmail: {
    fontSize: 12,
    fontWeight: '400',
    color: colors.textSoft,
  },
  removeText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  empty: {
    padding: 24,
    alignItems: 'center',
  },
  emptyText: {
    fontSize: 14,
    color: colors.textSoft,
  },
});
