import {StyleSheet} from 'react-native';
import {type AppColors} from '../../../theme';

export const createStyles = (colors: AppColors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 48,
    gap: 16,
  },
  main: {
    paddingHorizontal: 20,
    gap: 14,
  },
  pageHeader: {
    gap: 10,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  backBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.actionBlue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  titleCopy: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  pageTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: colors.textDark,
    letterSpacing: -0.675,
    lineHeight: 30,
  },
  pageSubtitle: {
    fontSize: 10.5,
    color: colors.textSoft,
    lineHeight: 15,
  },
  headerActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  outlineBtn: {
    height: 27,
    borderRadius: 18,
    borderWidth: 0.75,
    borderColor: 'rgba(224,229,235,0.7)',
    backgroundColor: colors.surface,
    paddingHorizontal: 13,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  outlineBtnText: {
    fontSize: 10.5,
    fontWeight: '500',
    color: colors.textDark,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 24,
    borderWidth: 0.75,
    borderColor: 'rgba(224,229,235,0.6)',
    padding: 19,
    gap: 12,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 3},
    shadowOpacity: 0.1,
    shadowRadius: 4.5,
    elevation: 3,
  },
  formPanel: {
    backgroundColor: 'rgba(237,242,248,0.3)',
    borderRadius: 21,
    borderWidth: 0.75,
    borderColor: 'rgba(224,229,235,0.6)',
    paddingHorizontal: 19,
    paddingTop: 31,
    paddingBottom: 19,
    gap: 18,
  },
  photoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 15,
  },
  photoBox: {
    width: 72,
    height: 72,
    borderRadius: 21,
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: colors.actionTint3,
    backgroundColor: colors.actionTint06,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    overflow: 'hidden',
  },
  photoImage: {
    width: '100%',
    height: '100%',
  },
  photoCopy: {
    flex: 1,
    minWidth: 0,
  },
  photoTitle: {
    fontSize: 10.5,
    fontWeight: '600',
    color: colors.textDark,
    lineHeight: 15,
  },
  photoHint: {
    fontSize: 9,
    color: colors.textSoft,
    lineHeight: 12,
    marginBottom: 6,
  },
  uploadBtn: {
    alignSelf: 'flex-start',
    height: 24,
    borderRadius: 18,
    borderWidth: 0.75,
    borderColor: colors.border,
    backgroundColor: '#F7FBFD',
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  uploadBtnText: {
    fontSize: 9,
    fontWeight: '500',
    color: colors.textDark,
  },
  fieldsStack: {
    gap: 12,
    width: '100%',
  },
  loginCard: {
    backgroundColor: colors.surface,
    borderRadius: 21,
    borderWidth: 0.75,
    borderColor: 'rgba(224,229,235,0.6)',
    padding: 13,
    gap: 12,
  },
  loginHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  loginCopy: {
    flex: 1,
    minWidth: 0,
  },
  loginTitle: {
    fontSize: 10.5,
    fontWeight: '600',
    color: colors.textDark,
    lineHeight: 15,
  },
  loginHint: {
    fontSize: 9,
    color: colors.textSoft,
    marginTop: 0,
    lineHeight: 12,
  },
  footer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingTop: 6,
  },
  prevBtn: {
    height: 27,
    borderRadius: 18,
    borderWidth: 0.75,
    borderColor: colors.border,
    backgroundColor: '#F7FBFD',
    paddingHorizontal: 13,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  prevBtnDisabled: {
    opacity: 0.5,
  },
  prevBtnText: {
    fontSize: 10.5,
    fontWeight: '500',
    color: colors.textDark,
  },
  nextBtn: {
    height: 27,
    borderRadius: 18,
    backgroundColor: colors.actionBlue,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  nextBtnText: {
    fontSize: 10.5,
    fontWeight: '500',
    color: colors.white,
  },
  stepBody: {
    gap: 18,
    width: '100%',
  },
  stepHint: {
    fontSize: 10.5,
    color: colors.textSoft,
    lineHeight: 15,
  },
});
