import {StyleSheet} from 'react-native';
import {type AppColors} from '../../../theme';

export const createStyles = (colors: AppColors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 40,
    gap: 14,
  },
  main: {
    width: '100%',
    maxWidth: 560,
    alignSelf: 'center',
    paddingHorizontal: 20,
    gap: 14,
  },
  pageHeader: {
    marginTop: 8,
  },
  titleLeft: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.actionBlue,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  titleBlock: {
    flex: 1,
    gap: 2,
  },
  pageTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.textDark,
    letterSpacing: -0.5,
    lineHeight: 28,
  },
  pageSubtitle: {
    fontSize: 12,
    fontWeight: '400',
    color: colors.textSoft,
    lineHeight: 18,
  },
  stepper: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  stepPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    height: 32,
    paddingHorizontal: 8,
    borderRadius: 999,
    backgroundColor: colors.surface,
    borderWidth: 0.75,
    borderColor: colors.borderSoft,
    flexShrink: 0,
  },
  stepPillCompleted: {
    backgroundColor: colors.actionTint1,
    borderColor: colors.actionTint35,
  },
  stepPillActive: {
    backgroundColor: colors.actionBlue,
    borderColor: colors.actionBlue,
    shadowColor: colors.actionBlue,
    shadowOffset: {width: 0, height: 3},
    shadowOpacity: 0.28,
    shadowRadius: 6,
    elevation: 3,
  },
  stepNumber: {
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.track,
  },
  stepNumberCompleted: {
    backgroundColor: colors.actionTint16,
  },
  stepNumberActive: {
    backgroundColor: 'rgba(255,255,255,0.25)',
  },
  stepNumberText: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.textSoft,
  },
  stepNumberTextCompleted: {
    color: colors.actionBlue,
  },
  stepNumberTextActive: {
    color: colors.white,
  },
  stepLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.textSoft,
  },
  stepLabelCompleted: {
    color: colors.actionBlue,
  },
  stepLabelActive: {
    color: colors.white,
  },
  stepConnector: {
    width: 4,
    height: 1,
    backgroundColor: colors.border,
  },
  stepConnectorCompleted: {
    backgroundColor: colors.actionTint35,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    borderWidth: 0.75,
    borderColor: colors.borderSoft,
    padding: 16,
    gap: 14,
    shadowColor: '#0B152C',
    shadowOffset: {width: 0, height: 3},
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 1,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textDark,
  },
  field: {
    gap: 6,
  },
  label: {
    fontSize: 10,
    fontWeight: '600',
    color: colors.textSoft,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  input: {
    height: 44,
    borderRadius: 12,
    borderWidth: 0.75,
    borderColor: colors.border,
    paddingHorizontal: 14,
    fontSize: 14,
    color: colors.textDark,
    backgroundColor: colors.surface,
  },
  textarea: {
    minHeight: 88,
    borderRadius: 12,
    borderWidth: 0.75,
    borderColor: colors.border,
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 12,
    fontSize: 14,
    color: colors.textDark,
    backgroundColor: colors.surface,
    textAlignVertical: 'top',
  },
  toggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  toggleCopy: {
    flex: 1,
    gap: 2,
  },
  toggleTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textDark,
  },
  toggleHint: {
    fontSize: 12,
    fontWeight: '400',
    color: colors.textSoft,
    lineHeight: 16,
  },
  optional: {
    fontSize: 10,
    fontWeight: '600',
    color: colors.textSoft,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  presetHeader: {
    gap: 2,
  },
  presetGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  presetCard: {
    width: '47.5%',
    flexGrow: 1,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    padding: 12,
    gap: 8,
  },
  presetCardActive: {
    borderColor: colors.actionBlue,
    backgroundColor: colors.actionTint06,
  },
  presetIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.track,
  },
  presetIconActive: {
    backgroundColor: colors.actionBlue,
  },
  presetTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textDark,
  },
  presetDescription: {
    fontSize: 11,
    fontWeight: '400',
    color: colors.textSoft,
    lineHeight: 15,
  },
  navRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  previousBtn: {
    height: 36,
    paddingHorizontal: 18,
    borderRadius: 999,
    borderWidth: 0.75,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  previousBtnDisabled: {
    opacity: 0.5,
  },
  previousBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textDark,
  },
  continueBtn: {
    height: 36,
    paddingHorizontal: 18,
    borderRadius: 999,
    backgroundColor: colors.actionBlue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  continueBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.white,
  },
  summaryTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textDark,
  },
  summaryList: {
    gap: 10,
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  summaryLabel: {
    fontSize: 13,
    fontWeight: '400',
    color: colors.textSoft,
  },
  summaryValue: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textDark,
  },
  summaryStatusActive: {
    color: colors.successBright,
  },
  summaryStatusInactive: {
    color: colors.warning,
  },
  matrixScroll: {
    marginHorizontal: -4,
  },
  matrix: {
    minWidth: 520,
    gap: 0,
  },
  matrixHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingBottom: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  matrixRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.borderSoft,
  },
  matrixModuleCol: {
    width: 88,
    paddingRight: 6,
  },
  matrixModuleHeader: {
    fontSize: 9,
    fontWeight: '700',
    color: colors.textSoft,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  matrixModuleLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textDark,
  },
  matrixRoleCol: {
    width: 78,
    alignItems: 'center',
    justifyContent: 'center',
  },
  matrixRoleHeader: {
    fontSize: 8,
    fontWeight: '700',
    color: colors.textSoft,
    letterSpacing: 0.3,
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  grantYes: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: 'rgba(32,180,107,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  grantYesText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.successBright,
  },
  grantNo: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: colors.actionTint12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  grantNoText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.actionBlue,
  },
  userList: {
    gap: 10,
  },
  userRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  userAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  userAvatarText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.white,
  },
  userInfo: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  userName: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textDark,
  },
  userEmail: {
    fontSize: 12,
    fontWeight: '400',
    color: colors.textSoft,
  },
  assignBtn: {
    height: 32,
    paddingHorizontal: 14,
    borderRadius: 10,
    borderWidth: 0.75,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  assignBtnActive: {
    borderColor: colors.actionBlue,
    backgroundColor: colors.actionTint08,
  },
  assignBtnText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textDark,
  },
  assignBtnTextActive: {
    color: colors.actionBlue,
  },
  reviewGrid: {
    gap: 14,
  },
  reviewRow: {
    flexDirection: 'row',
    gap: 12,
  },
  reviewCell: {
    flex: 1,
    gap: 4,
  },
  reviewCellFull: {
    flex: 1,
    gap: 4,
  },
  reviewLabel: {
    fontSize: 10,
    fontWeight: '600',
    color: colors.textSoft,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  reviewValue: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textDark,
  },
});
