import {StyleSheet} from 'react-native';
import {type AppColors} from '../../../theme';

export const createStyles = (colors: AppColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    scroll: {
      flex: 1,
    },
    scrollContent: {
      paddingBottom: 48,
    },
    main: {
      paddingHorizontal: 20,
      gap: 14,
      paddingTop: 8,
    },
    backLink: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      alignSelf: 'flex-start',
    },
    backLinkText: {
      fontSize: 11,
      fontWeight: '500',
      color: colors.textSoft,
    },
    card: {
      backgroundColor: colors.surface,
      borderRadius: 24,
      borderWidth: 0.75,
      borderColor: colors.borderSoft,
      padding: 16,
      gap: 14,
      shadowColor: '#0F172A',
      shadowOffset: {width: 0, height: 4},
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 3,
    },
    formPanel: {
      backgroundColor: 'rgba(237,242,248,0.35)',
      borderRadius: 21,
      borderWidth: 0.75,
      borderColor: colors.borderSoft,
      paddingHorizontal: 16,
      paddingTop: 20,
      paddingBottom: 16,
      gap: 14,
    },
    stepEyebrow: {
      fontSize: 9,
      fontWeight: '700',
      color: colors.actionBlue,
      letterSpacing: 0.5,
      textTransform: 'uppercase',
    },
    stepTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.textDark,
      letterSpacing: -0.3,
    },
    stepDescription: {
      fontSize: 10.5,
      color: colors.textSoft,
      lineHeight: 16,
    },
    search: {
      height: 34,
      borderRadius: 18,
      backgroundColor: colors.searchBg,
      borderWidth: 0.75,
      borderColor: colors.borderSoft,
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 12,
      gap: 8,
    },
    searchInput: {
      flex: 1,
      fontSize: 11,
      color: colors.textDark,
      padding: 0,
    },
    customerList: {
      gap: 8,
    },
    customerCard: {
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.borderSoft,
      backgroundColor: colors.surface,
      paddingHorizontal: 12,
      paddingVertical: 10,
      gap: 4,
    },
    customerCardSelected: {
      borderColor: colors.actionBlue,
      backgroundColor: colors.actionTint06,
    },
    customerTop: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
    },
    customerCode: {
      fontSize: 9,
      fontWeight: '700',
      color: colors.textSoft,
      letterSpacing: 0.4,
    },
    tierBadge: {
      paddingHorizontal: 6,
      paddingVertical: 2,
      borderRadius: 999,
    },
    tierText: {
      fontSize: 7.5,
      fontWeight: '700',
    },
    customerName: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.textDark,
    },
    customerMeta: {
      fontSize: 9,
      color: colors.textSoft,
      lineHeight: 13,
    },
    durationBox: {
      borderRadius: 16,
      backgroundColor: colors.actionTint06,
      borderWidth: 0.75,
      borderColor: colors.actionTint15,
      padding: 14,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    durationLabel: {
      fontSize: 9,
      fontWeight: '700',
      color: colors.textSoft,
      letterSpacing: 0.5,
    },
    durationValue: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.textDark,
    },
    durationPrice: {
      fontSize: 11,
      fontWeight: '600',
      color: colors.actionBlue,
    },
    addonCard: {
      borderRadius: 16,
      borderWidth: 0.75,
      borderColor: colors.borderSoft,
      backgroundColor: colors.surface,
      padding: 14,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    addonCardSelected: {
      borderColor: colors.actionBlue,
      backgroundColor: colors.actionTint06,
    },
    addonCopy: {
      flex: 1,
      gap: 3,
    },
    addonTitle: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.textDark,
    },
    addonDescription: {
      fontSize: 10,
      color: colors.textSoft,
      lineHeight: 14,
    },
    addonPrice: {
      fontSize: 11,
      fontWeight: '700',
      color: colors.actionBlue,
    },
    checkCircle: {
      width: 22,
      height: 22,
      borderRadius: 11,
      borderWidth: 1,
      borderColor: colors.borderSoft,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.surface,
    },
    checkCircleSelected: {
      backgroundColor: colors.actionBlue,
      borderColor: colors.actionBlue,
    },
    insuranceCard: {
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.borderSoft,
      backgroundColor: colors.surface,
      padding: 14,
      gap: 8,
      position: 'relative',
    },
    insuranceCardSelected: {
      borderColor: colors.actionBlue,
      backgroundColor: colors.actionTint06,
    },
    popularBadge: {
      position: 'absolute',
      top: 10,
      right: 10,
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 999,
      backgroundColor: 'rgba(245,158,11,0.14)',
    },
    popularText: {
      fontSize: 7.5,
      fontWeight: '700',
      color: '#D97706',
      letterSpacing: 0.3,
    },
    insuranceTop: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    radio: {
      width: 18,
      height: 18,
      borderRadius: 9,
      borderWidth: 1.5,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    radioSelected: {
      borderColor: colors.actionBlue,
    },
    radioDot: {
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: colors.actionBlue,
    },
    insuranceTitle: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.textDark,
    },
    insuranceDescription: {
      fontSize: 10,
      color: colors.textSoft,
      paddingLeft: 28,
    },
    insurancePrice: {
      fontSize: 11,
      fontWeight: '700',
      color: colors.actionBlue,
      paddingLeft: 28,
    },
    summaryBox: {
      borderRadius: 16,
      backgroundColor: colors.actionTint06,
      borderWidth: 0.75,
      borderColor: colors.actionTint15,
      padding: 14,
      gap: 8,
    },
    summaryRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 12,
    },
    summaryLabel: {
      fontSize: 10.5,
      color: colors.textSoft,
    },
    summaryValue: {
      fontSize: 10.5,
      fontWeight: '600',
      color: colors.textDark,
      textAlign: 'right',
      flex: 1,
    },
    summaryTotal: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.actionBlue,
    },
    footer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      paddingTop: 4,
    },
    prevBtn: {
      height: 32,
      borderRadius: 18,
      borderWidth: 0.75,
      borderColor: colors.border,
      backgroundColor: '#F7FBFD',
      paddingHorizontal: 14,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    prevBtnDisabled: {
      opacity: 0.45,
    },
    prevBtnText: {
      fontSize: 11,
      fontWeight: '500',
      color: colors.textDark,
    },
    nextBtn: {
      height: 32,
      borderRadius: 18,
      backgroundColor: colors.actionBlue,
      paddingHorizontal: 16,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    nextBtnText: {
      fontSize: 11,
      fontWeight: '600',
      color: colors.white,
    },
    paymentMethodCard: {
      borderRadius: 16,
      borderWidth: 1,
      borderColor: colors.borderSoft,
      backgroundColor: 'rgba(237,242,248,0.55)',
      paddingHorizontal: 14,
      paddingVertical: 12,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    paymentMethodCardSelected: {
      borderColor: colors.actionBlue,
      backgroundColor: colors.actionTint06,
    },
    paymentMethodLabel: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.textDark,
    },
    paymentFields: {
      gap: 12,
      paddingTop: 4,
    },
    reviewGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    reviewCell: {
      width: '48%',
      flexGrow: 1,
      minWidth: '46%',
      borderRadius: 14,
      backgroundColor: colors.surface,
      borderWidth: 0.75,
      borderColor: colors.borderSoft,
      padding: 12,
      gap: 4,
      minHeight: 68,
    },
    reviewLabel: {
      fontSize: 8.5,
      fontWeight: '700',
      color: colors.textSoft,
      letterSpacing: 0.3,
      textTransform: 'uppercase',
    },
    reviewValue: {
      fontSize: 10,
      fontWeight: '600',
      color: colors.textDark,
      lineHeight: 14,
    },
    disclaimer: {
      fontSize: 9,
      color: colors.textSoft,
      lineHeight: 14,
    },
    sectionCard: {
      backgroundColor: colors.surface,
      borderRadius: 24,
      borderWidth: 0.75,
      borderColor: colors.borderSoft,
      padding: 16,
      gap: 12,
      shadowColor: '#0F172A',
      shadowOffset: {width: 0, height: 4},
      shadowOpacity: 0.06,
      shadowRadius: 10,
      elevation: 2,
    },
    sectionEyebrow: {
      fontSize: 9,
      fontWeight: '700',
      color: colors.textSoft,
      letterSpacing: 0.5,
      textTransform: 'uppercase',
    },
    summaryHero: {
      borderRadius: 16,
      backgroundColor: colors.actionTint06,
      borderWidth: 0.75,
      borderColor: colors.actionTint15,
      padding: 14,
      gap: 10,
    },
    summaryHeroRow: {
      gap: 3,
    },
    summaryHeroLabel: {
      fontSize: 8.5,
      fontWeight: '700',
      color: colors.textSoft,
      letterSpacing: 0.3,
      textTransform: 'uppercase',
    },
    summaryHeroValue: {
      fontSize: 11,
      fontWeight: '700',
      color: colors.textDark,
    },
    totalLine: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingTop: 4,
    },
    totalLabel: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.textDark,
    },
    totalValue: {
      fontSize: 20,
      fontWeight: '700',
      color: colors.actionBlue,
      letterSpacing: -0.4,
    },
    selectedAddonRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
      paddingVertical: 4,
    },
    selectedAddonLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      flex: 1,
    },
    selectedAddonTitle: {
      fontSize: 11,
      fontWeight: '600',
      color: colors.textDark,
      flex: 1,
    },
    selectedAddonPrice: {
      fontSize: 10,
      fontWeight: '700',
      color: colors.actionBlue,
    },
  });
