import {StyleSheet} from 'react-native';
import {type AppColors} from '../../../theme';

export const createStyles = (colors: AppColors) =>
  StyleSheet.create({
    container: {flex: 1, backgroundColor: colors.background},
    scroll: {flex: 1},
    scrollContent: {paddingBottom: 48},
    main: {paddingHorizontal: 20, gap: 14, paddingTop: 8},
    topBar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    backBtn: {
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: '#7C3AED',
      alignItems: 'center',
      justifyContent: 'center',
    },
    topTitle: {
      flex: 1,
      textAlign: 'center',
      fontSize: 16,
      fontWeight: '700',
      color: colors.textDark,
      letterSpacing: -0.3,
    },
    topActions: {flexDirection: 'row', alignItems: 'center', gap: 8},
    topIconBtn: {
      width: 30,
      height: 30,
      borderRadius: 15,
      backgroundColor: colors.surface,
      borderWidth: 0.75,
      borderColor: colors.borderSoft,
      alignItems: 'center',
      justifyContent: 'center',
    },
    notifyDot: {
      position: 'absolute',
      top: 6,
      right: 6,
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: colors.error,
    },
    breadcrumb: {
      fontSize: 10,
      fontWeight: '600',
      color: colors.actionBlue,
    },
    pageHeaderRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 10,
    },
    pageHeaderCopy: {flex: 1, gap: 4},
    pageTitle: {
      fontSize: 22,
      fontWeight: '800',
      color: colors.textDark,
      letterSpacing: -0.6,
    },
    pageSubtitle: {
      fontSize: 10.5,
      color: colors.textSoft,
      lineHeight: 15,
    },
    headerActions: {flexDirection: 'row', gap: 8, paddingTop: 4},
    cancelBtn: {
      height: 34,
      paddingHorizontal: 12,
      borderRadius: 18,
      borderWidth: 0.75,
      borderColor: colors.borderSoft,
      backgroundColor: colors.surface,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
    },
    cancelText: {fontSize: 10, fontWeight: '600', color: colors.textDark},
    saveBtn: {
      height: 34,
      paddingHorizontal: 12,
      borderRadius: 18,
      backgroundColor: colors.actionBlue,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
    },
    saveText: {fontSize: 10, fontWeight: '700', color: colors.white},
    previewCard: {
      borderRadius: 22,
      backgroundColor: colors.surface,
      borderWidth: 0.75,
      borderColor: colors.borderSoft,
      overflow: 'hidden',
      shadowColor: '#0F172A',
      shadowOffset: {width: 0, height: 4},
      shadowOpacity: 0.07,
      shadowRadius: 10,
      elevation: 2,
    },
    previewImageWrap: {
      height: 150,
      alignItems: 'center',
      justifyContent: 'center',
      padding: 12,
    },
    previewImage: {width: '100%', height: '100%'},
    previewBody: {paddingHorizontal: 16, paddingBottom: 14, gap: 10},
    previewMakeYear: {
      fontSize: 10,
      fontWeight: '600',
      color: colors.textSoft,
    },
    previewTitle: {
      fontSize: 18,
      fontWeight: '800',
      color: colors.textDark,
      letterSpacing: -0.4,
    },
    toggleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      paddingTop: 4,
      borderTopWidth: 0.75,
      borderTopColor: colors.borderSoft,
    },
    toggleCopy: {flex: 1, gap: 2},
    toggleTitle: {fontSize: 11, fontWeight: '700', color: colors.textDark},
    toggleSubtitle: {fontSize: 9.5, color: colors.textSoft},
    quickNavCard: {
      borderRadius: 18,
      backgroundColor: colors.surface,
      borderWidth: 0.75,
      borderColor: colors.borderSoft,
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    quickNavRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 8,
    },
    quickNavItem: {
      flex: 1,
      alignItems: 'center',
      gap: 5,
      paddingVertical: 4,
      borderRadius: 12,
    },
    quickNavItemActive: {
      backgroundColor: colors.actionTint06,
    },
    quickNavLabel: {
      fontSize: 8.5,
      fontWeight: '600',
      color: colors.textSoft,
      textAlign: 'center',
    },
    quickNavLabelActive: {color: colors.actionBlue},
    sectionCard: {
      borderRadius: 22,
      backgroundColor: colors.surface,
      borderWidth: 0.75,
      borderColor: colors.borderSoft,
      padding: 16,
      gap: 12,
      shadowColor: '#0F172A',
      shadowOffset: {width: 0, height: 3},
      shadowOpacity: 0.05,
      shadowRadius: 8,
      elevation: 2,
    },
    sectionTitle: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.textDark,
      letterSpacing: -0.3,
    },
    sectionSubtitle: {
      fontSize: 10,
      color: colors.textSoft,
      marginTop: -6,
    },
    tripleRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    tripleChild: {
      width: '31%',
      flexGrow: 1,
      minWidth: '30%',
    },
    mediaGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    mediaAdd: {
      width: '31%',
      minWidth: 96,
      aspectRatio: 1,
      borderRadius: 14,
      borderWidth: 1.2,
      borderStyle: 'dashed',
      borderColor: colors.actionBlue,
      backgroundColor: colors.actionTint04,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      padding: 8,
    },
    mediaAddText: {
      fontSize: 9,
      fontWeight: '600',
      color: colors.actionBlue,
      textAlign: 'center',
    },
    mediaThumb: {
      width: '31%',
      minWidth: 96,
      aspectRatio: 1,
      borderRadius: 14,
      backgroundColor: 'rgba(237,242,248,0.9)',
      borderWidth: 0.75,
      borderColor: colors.borderSoft,
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
      padding: 8,
    },
    mediaImage: {width: '100%', height: '100%'},
  });
