import {StyleSheet} from 'react-native';
import {type AppColors} from '../../../theme';

export const createStyles = (colors: AppColors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 32,
    gap: 16,
  },
  main: {
    paddingHorizontal: 20,
    gap: 18,
  },
  pageHeader: {
    gap: 10,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  backBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.actionBlue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pageTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: colors.textDark,
    letterSpacing: -0.6,
  },
  pageSubtitle: {
    fontSize: 10.5,
    color: colors.textSoft,
    marginTop: 3,
  },
  actions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 6,
  },
  secondaryBtn: {
    height: 27,
    paddingHorizontal: 13,
    borderRadius: 18,
    backgroundColor: colors.surface,
    borderWidth: 0.75,
    borderColor: colors.borderSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryBtnText: {
    fontSize: 10.5,
    fontWeight: '500',
    color: colors.textDark,
  },
  primaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    height: 27,
    paddingHorizontal: 12,
    borderRadius: 18,
    backgroundColor: colors.actionBlue,
  },
  primaryBtnText: {
    fontSize: 10.5,
    fontWeight: '500',
    color: colors.white,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 24,
    borderWidth: 0.75,
    borderColor: colors.borderSoft,
    padding: 19,
    gap: 12,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 3},
    shadowOpacity: 0.1,
    shadowRadius: 4.5,
    elevation: 2,
  },
  stepEyebrow: {
    fontSize: 9,
    fontWeight: '600',
    color: colors.textSoft,
    letterSpacing: 0.9,
    textTransform: 'uppercase',
  },
  stepTitle: {
    fontSize: 13.5,
    fontWeight: '700',
    color: colors.textDark,
    marginTop: 3,
  },
  vehicleCard: {
    flexDirection: 'row',
    gap: 15,
    borderRadius: 21,
    padding: 15,
    backgroundColor: '#DBEAFE',
  },
  vehicleImageWrap: {
    width: 140,
    height: 96,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    backgroundColor: 'rgba(255,255,255,0.45)',
  },
  vehicleImage: {
    width: 132,
    height: 88,
  },
  vehicleInfo: {
    flex: 1,
    justifyContent: 'center',
    gap: 2,
  },
  vin: {
    fontSize: 9,
    color: colors.actionBlue,
  },
  vehicleTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.textDark,
    lineHeight: 21,
  },
  vehicleSpecs: {
    fontSize: 10.5,
    color: colors.textSoft,
    lineHeight: 15,
  },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 9,
  },
  statCell: {
    width: '47.5%',
    flexGrow: 1,
    minHeight: 62,
    borderRadius: 21,
    borderWidth: 0.75,
    borderColor: colors.borderSoft,
    backgroundColor: 'rgba(237,242,248,0.4)',
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  statIcon: {
    width: 33,
    height: 33,
    borderRadius: 18,
    backgroundColor: colors.actionTint1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statLabel: {
    fontSize: 8.25,
    color: colors.textSoft,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  statValue: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textDark,
  },
  statNote: {
    fontSize: 8.25,
    color: colors.actionBlue,
  },
  chargesList: {
    width: '100%',
    gap: 9,
  },
  chargeRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    borderRadius: 18,
    borderWidth: 0.75,
    borderColor: 'rgba(224,229,235,0.6)',
    backgroundColor: colors.surface,
    padding: 9.75,
  },
  chargeLabel: {
    flexShrink: 0,
    fontSize: 9,
    fontWeight: '500',
    color: colors.textDark,
    lineHeight: 12,
  },
  chargeInputWrap: {
    flex: 1,
    minWidth: 84,
    height: 27,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  chargeInput: {
    width: '100%',
    maxWidth: 84,
    minWidth: 72,
    height: 27,
    borderRadius: 15,
    borderWidth: 0.75,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: 9.75,
    paddingVertical: 0,
    textAlign: 'right',
    fontSize: 10.5,
    fontWeight: '600',
    color: colors.textDark,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 0.75},
    shadowOpacity: 0.1,
    shadowRadius: 2.25,
    elevation: 1,
  },
  invoiceSummary: {
    flexDirection: 'row',
    borderRadius: 21,
    backgroundColor: 'rgba(237,242,248,0.6)',
    padding: 12,
    gap: 12,
  },
  invoiceSummaryCol: {
    flex: 1,
    gap: 2,
  },
  invoiceLabel: {
    fontSize: 8.25,
    color: colors.textSoft,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  invoiceValue: {
    fontSize: 13.5,
    fontWeight: '700',
    color: colors.textDark,
  },
  lineRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  lineLabel: {
    fontSize: 10.5,
    color: colors.textSoft,
  },
  lineValue: {
    fontSize: 10.5,
    fontWeight: '600',
    color: colors.textDark,
  },
  refundValue: {
    color: colors.successBright,
  },
  totalRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderTopWidth: 0.75,
    borderTopColor: colors.borderSoft,
    paddingTop: 10,
    marginTop: 4,
  },
  totalLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textDark,
  },
  totalValue: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.actionBlue,
  },
  chargeBtn: {
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.actionBlue,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 4,
  },
  chargeBtnText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.white,
  },
  loading: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
