import {StyleSheet} from 'react-native';
import {type AppColors} from '../../../theme';

export const createStyles = (colors: AppColors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 40,
    gap: 14,
  },
  main: {
    width: '100%',
    maxWidth: 560,
    alignSelf: 'center',
    paddingHorizontal: 20,
    gap: 14,
  },
  pageHeader: {
    marginTop: 8,
    gap: 12,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.actionBlue,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  titleBlock: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  pageTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.textDark,
    letterSpacing: -0.5,
    lineHeight: 28,
  },
  pageSubtitle: {
    fontSize: 12,
    fontWeight: '400',
    color: colors.textSoft,
    lineHeight: 18,
  },
  actionsRow: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: 8,
  },
  cancelBtn: {
    height: 36,
    paddingHorizontal: 16,
    borderRadius: 999,
    borderWidth: 0.75,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelBtnText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textDark,
  },
  saveBtn: {
    height: 36,
    paddingHorizontal: 14,
    borderRadius: 999,
    backgroundColor: colors.actionBlue,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  saveBtnText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.white,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    borderWidth: 0.75,
    borderColor: colors.borderSoft,
    padding: 16,
    gap: 14,
    shadowColor: '#0B152C',
    shadowOffset: {width: 0, height: 3},
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 1,
  },
  sectionHeader: {
    gap: 2,
  },
  sectionEyebrow: {
    fontSize: 10,
    fontWeight: '600',
    color: colors.textSoft,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textDark,
  },
  matrixScroll: {
    marginHorizontal: -4,
  },
  matrix: {
    minWidth: 520,
  },
  matrixHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingBottom: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  matrixRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.borderSoft,
  },
  matrixModuleCol: {
    width: 88,
    paddingRight: 6,
  },
  matrixModuleHeader: {
    fontSize: 9,
    fontWeight: '700',
    color: colors.textSoft,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  matrixModuleLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textDark,
  },
  matrixRoleCol: {
    width: 78,
    alignItems: 'center',
    justifyContent: 'center',
  },
  matrixRoleHeader: {
    fontSize: 8,
    fontWeight: '700',
    color: colors.textSoft,
    letterSpacing: 0.3,
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  grantYes: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: 'rgba(32,180,107,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  grantYesText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.successBright,
  },
  grantNo: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: colors.track,
    alignItems: 'center',
    justifyContent: 'center',
  },
  grantNoText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.textSoft,
  },
  field: {
    gap: 6,
  },
  label: {
    fontSize: 10,
    fontWeight: '600',
    color: colors.textSoft,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  input: {
    height: 44,
    borderRadius: 12,
    borderWidth: 0.75,
    borderColor: colors.border,
    paddingHorizontal: 14,
    fontSize: 14,
    color: colors.textDark,
    backgroundColor: colors.surface,
  },
  textarea: {
    minHeight: 88,
    borderRadius: 12,
    borderWidth: 0.75,
    borderColor: colors.border,
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 12,
    fontSize: 14,
    color: colors.textDark,
    backgroundColor: colors.surface,
    textAlignVertical: 'top',
  },
  toggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  toggleCopy: {
    flex: 1,
    gap: 2,
  },
  toggleTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.textDark,
  },
  toggleHint: {
    fontSize: 12,
    fontWeight: '400',
    color: colors.textSoft,
    lineHeight: 16,
  },
  summaryList: {
    gap: 10,
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  summaryLabel: {
    fontSize: 13,
    fontWeight: '400',
    color: colors.textSoft,
  },
  summaryValue: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textDark,
  },
  summaryStatusActive: {
    color: colors.successBright,
  },
  summaryStatusInactive: {
    color: colors.warning,
  },
});
