import {StyleSheet} from 'react-native';
import {type AppColors, spacing} from '../../../theme';

const cardShadow = {
  shadowColor: '#0B152C',
  shadowOffset: {width: 0, height: 8},
  shadowOpacity: 0.08,
  shadowRadius: 12,
  elevation: 3,
};

export const createStyles = (colors: AppColors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: 32,
    gap: spacing.md,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: spacing.md,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  logoBadge: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.brandBlue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dateLabel: {
    fontSize: 11,
    fontWeight: '400',
    color: colors.textSecondary,
    letterSpacing: 0.55,
    textTransform: 'uppercase',
  },
  welcome: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
    marginTop: 2,
  },
  welcomeName: {
    color: colors.secondary,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  iconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.surface,
    alignItems: 'center',
    justifyContent: 'center',
    ...cardShadow,
  },
  notificationDot: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.notification,
  },
  main: {
    paddingHorizontal: 20,
    paddingTop: 4,
    gap: 20,
  },
  fleetCard: {
    backgroundColor: colors.fleetEnd,
    borderRadius: 28,
    padding: 20,
    gap: 8,
    overflow: 'hidden',
    ...cardShadow,
  },
  fleetTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  fleetBadge: {
    backgroundColor: 'rgba(255,255,255,0.78)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    alignSelf: 'flex-start',
  },
  fleetBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.onPastelMuted,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  fleetTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.textDark,
    marginTop: 6,
  },
  fleetSubtitle: {
    fontSize: 12,
    color: colors.textSecondary,
    marginTop: 2,
  },
  exploreButton: {
    backgroundColor: 'rgba(11,17,31,0.88)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
  },
  exploreText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  fleetImageWrap: {
    alignItems: 'center',
    height: 128,
    justifyContent: 'center',
  },
  fleetImage: {
    width: 205,
    height: 128,
  },
  fleetStats: {
    flexDirection: 'row',
    gap: 8,
  },
  fleetStat: {
    flex: 1,
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderRadius: 20,
    paddingVertical: 8,
    alignItems: 'center',
  },
  fleetStatValue: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.onPastel,
  },
  fleetStatLabel: {
    fontSize: 10,
    color: colors.onPastelMuted,
  },
  metricsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  metricCard: {
    width: '47.5%',
    flexGrow: 1,
    borderRadius: 24,
    padding: 16,
    minHeight: 120,
    ...cardShadow,
  },
  metricTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  metricIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.8)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  changeBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    backgroundColor: 'rgba(255,255,255,0.8)',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 999,
  },
  changeText: {
    fontSize: 10,
    fontWeight: '700',
  },
  changePositive: {
    color: colors.success,
  },
  changeNegative: {
    color: colors.error,
  },
  metricLabel: {
    fontSize: 11,
    color: colors.textMuted,
    marginTop: 15,
  },
  metricValue: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.text,
    letterSpacing: -0.5,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 24,
    padding: 20,
    gap: 12,
    ...cardShadow,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionEyebrow: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.textSecondary,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.text,
  },
  sectionMeta: {
    fontSize: 12,
    color: colors.textSecondary,
  },
  link: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.secondary,
  },
  statusBar: {
    height: 10,
    borderRadius: 999,
    backgroundColor: colors.track,
    flexDirection: 'row',
    overflow: 'hidden',
  },
  statusSegment: {
    height: '100%',
  },
  statusGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    paddingTop: 4,
  },
  statusItem: {
    width: '47%',
    flexGrow: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  statusLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  statusLabel: {
    fontSize: 12,
    color: 'rgba(11,17,31,0.8)',
  },
  statusCount: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.text,
  },
  revenueHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  revenueAmountRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 8,
    marginTop: 4,
  },
  revenueAmount: {
    fontSize: 24,
    fontWeight: '700',
    color: colors.text,
    letterSpacing: -0.6,
  },
  revenueGrowth: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.growth,
    marginBottom: 4,
  },
  periodToggle: {
    flexDirection: 'row',
    backgroundColor: colors.track,
    borderRadius: 999,
    padding: 4,
  },
  periodButton: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  periodButtonActive: {
    backgroundColor: colors.surface,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  periodText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.textSecondary,
  },
  periodTextActive: {
    color: colors.text,
  },
  chart: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    height: 128,
    gap: 8,
  },
  chartColumn: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 6,
  },
  chartBar: {
    width: '70%',
    borderRadius: 8,
    backgroundColor: colors.secondary,
    minHeight: 8,
  },
  chartLabel: {
    fontSize: 10,
    color: colors.textSecondary,
  },
  orderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  orderRowLast: {
    borderBottomWidth: 0,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.brandBlue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.white,
  },
  orderInfo: {
    flex: 1,
  },
  orderName: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.text,
  },
  orderDetail: {
    fontSize: 12,
    color: colors.textSecondary,
    marginTop: 2,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 999,
  },
  statusBadgeText: {
    fontSize: 10,
    fontWeight: '700',
  },
  activityRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  activityIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  activityInfo: {
    flex: 1,
  },
  activityMessage: {
    fontSize: 14,
    color: colors.text,
    lineHeight: 19,
  },
  activityTime: {
    fontSize: 11,
    color: colors.textSecondary,
    marginTop: 2,
  },
  emptyHint: {
    fontSize: 13,
    color: colors.textSoft,
    paddingVertical: 8,
  },
  loading: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
