import {StyleSheet} from 'react-native';
import {type AppColors} from '../../../theme';

export const createStyles = (colors: AppColors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 40,
    gap: 16,
  },
  main: {
    width: '100%',
    maxWidth: 560,
    alignSelf: 'center',
    paddingHorizontal: 20,
    gap: 16,
  },
  pageHeader: {
    marginTop: 8,
    gap: 14,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  backBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.actionBlue,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  titleBlock: {
    flex: 1,
    gap: 2,
  },
  pageTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.textDark,
    letterSpacing: -0.5,
    lineHeight: 28,
  },
  pageSubtitle: {
    fontSize: 11,
    fontWeight: '400',
    color: colors.textSoft,
    lineHeight: 16,
  },
  actions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 8,
  },
  secondaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    height: 30,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: colors.surface,
    borderWidth: 0.75,
    borderColor: colors.border,
  },
  secondaryBtnText: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.textDark,
  },
  primaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    height: 30,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: colors.actionBlue,
  },
  primaryBtnText: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.white,
  },
  metricsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  pipelineCard: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    borderWidth: 0.75,
    borderColor: colors.borderSoft,
    padding: 16,
    gap: 14,
    shadowColor: '#0B152C',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 2,
  },
  pipelineHeader: {
    gap: 3,
  },
  pipelineEyebrow: {
    fontSize: 9,
    fontWeight: '600',
    color: colors.textSoft,
    letterSpacing: 0.9,
    textTransform: 'uppercase',
  },
  pipelineTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.textDark,
  },
  pipelineGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  stageItem: {
    width: '31%',
    flexGrow: 1,
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 4,
    minHeight: 82,
    justifyContent: 'space-between',
  },
  stageItemWide: {
    width: '47.5%',
  },
  stageLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.92)',
  },
  stageCount: {
    fontSize: 22,
    fontWeight: '700',
    color: colors.white,
    letterSpacing: -0.5,
    lineHeight: 26,
  },
  stageStatus: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    marginTop: 2,
  },
  stageStatusText: {
    fontSize: 9,
    fontWeight: '600',
    color: colors.white,
  },
  shortlistCard: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    borderWidth: 0.75,
    borderColor: colors.borderSoft,
    padding: 16,
    gap: 12,
    shadowColor: '#0B152C',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 2,
  },
  shortlistHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  shortlistHeaderText: {
    flex: 1,
    gap: 3,
  },
  sectionEyebrow: {
    fontSize: 9,
    fontWeight: '600',
    color: colors.textSoft,
    letterSpacing: 0.9,
    textTransform: 'uppercase',
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.textDark,
  },
  gradIcon: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.track,
    alignItems: 'center',
    justifyContent: 'center',
  },
  candidateList: {
    gap: 10,
  },
  candidateCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: 14,
    borderWidth: 0.75,
    borderColor: colors.borderSoft,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 10,
  },
  candidateAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
  },
  candidateAvatarText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.white,
  },
  candidateBody: {
    flex: 1,
    gap: 4,
  },
  candidateName: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textDark,
  },
  candidateRole: {
    fontSize: 11,
    fontWeight: '400',
    color: colors.textSoft,
  },
  stageBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 7,
    paddingVertical: 2,
    borderRadius: 999,
  },
  stageBadgeText: {
    fontSize: 9,
    fontWeight: '600',
  },
  scoreBlock: {
    alignItems: 'flex-end',
    minWidth: 40,
  },
  scoreText: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.actionBlue,
    letterSpacing: -0.5,
    lineHeight: 24,
  },
  scoreLabel: {
    fontSize: 8,
    fontWeight: '600',
    color: colors.textSoft,
    letterSpacing: 0.6,
  },
});
