import {StyleSheet} from 'react-native';
import {type AppColors} from '../../../theme';

export const createStyles = (colors: AppColors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 40,
    gap: 14,
  },
  main: {
    width: '100%',
    maxWidth: 560,
    alignSelf: 'center',
    paddingHorizontal: 20,
    gap: 14,
  },
  pageHeader: {
    marginTop: 8,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  backBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.actionBlue,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  titleBlock: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  pageTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.textDark,
    letterSpacing: -0.5,
    lineHeight: 28,
  },
  pageSubtitle: {
    fontSize: 12,
    fontWeight: '400',
    color: colors.textSoft,
    lineHeight: 16,
  },
  stepperScroll: {
    flexGrow: 0,
    marginHorizontal: -4,
  },
  stepperContent: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 4,
    paddingVertical: 2,
  },
  stepPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    height: 34,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: colors.track,
    borderWidth: 1,
    borderColor: colors.borderSoft,
  },
  stepPillDone: {
    backgroundColor: colors.actionTint08,
    borderColor: colors.actionTint2,
  },
  stepPillActive: {
    backgroundColor: colors.actionTint12,
    borderColor: colors.actionBlue,
  },
  stepNumber: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: '#D8DEE8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepNumberActive: {
    backgroundColor: colors.actionBlue,
  },
  stepNumberText: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.textSecondary,
  },
  stepNumberTextActive: {
    color: colors.white,
  },
  stepPillText: {
    fontSize: 11,
    fontWeight: '600',
    color: colors.textSecondary,
  },
  stepPillTextActive: {
    color: colors.actionBlue,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    borderWidth: 0.75,
    borderColor: colors.borderSoft,
    padding: 16,
    gap: 14,
    shadowColor: '#0B152C',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 2,
  },
  fieldsGrid: {
    gap: 12,
  },
  fieldRow: {
    flexDirection: 'row',
    gap: 10,
  },
  field: {
    flex: 1,
    gap: 6,
  },
  fieldFull: {
    gap: 6,
  },
  label: {
    fontSize: 9,
    fontWeight: '600',
    color: colors.textSoft,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  inputWrap: {
    minHeight: 40,
    borderRadius: 12,
    borderWidth: 0.75,
    borderColor: colors.border,
    backgroundColor: colors.searchBg,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  input: {
    flex: 1,
    fontSize: 13,
    fontWeight: '500',
    color: colors.textDark,
    paddingVertical: 10,
  },
  textareaWrap: {
    minHeight: 72,
    borderRadius: 12,
    borderWidth: 0.75,
    borderColor: colors.border,
    backgroundColor: colors.searchBg,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  textarea: {
    fontSize: 13,
    fontWeight: '400',
    color: colors.textDark,
    textAlignVertical: 'top',
    minHeight: 52,
    paddingVertical: 0,
  },
  footer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingTop: 4,
  },
  backStepBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    height: 36,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: colors.track,
  },
  backStepBtnDisabled: {
    opacity: 0.45,
  },
  backStepBtnText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textDark,
  },
  draftBtn: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    height: 36,
  },
  draftBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textDark,
  },
  continueBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    height: 36,
    paddingHorizontal: 14,
    borderRadius: 12,
    backgroundColor: colors.actionBlue,
  },
  continueBtnText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.white,
  },
  previewBox: {
    backgroundColor: colors.track,
    borderRadius: 14,
    padding: 14,
    gap: 6,
  },
  previewEyebrow: {
    fontSize: 9,
    fontWeight: '600',
    color: colors.textSoft,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  previewTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.textDark,
  },
  previewDescription: {
    fontSize: 12,
    fontWeight: '400',
    color: colors.textSoft,
    lineHeight: 17,
  },
  reviewGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  reviewCard: {
    width: '47.5%',
    flexGrow: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    padding: 12,
    borderRadius: 14,
    borderWidth: 0.75,
    borderColor: colors.borderSoft,
    backgroundColor: colors.surface,
  },
  reviewIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.actionTint12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reviewCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  reviewLabel: {
    fontSize: 9,
    fontWeight: '600',
    color: colors.textSoft,
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  reviewValue: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textDark,
  },
});
