import type {FeedPost} from '../CustomerHome/module';

export const SAVED_POSTS: FeedPost[] = [
  {
    id: 'saved-bmw',
    sellerInitials: 'AW',
    sellerName: 'Auto World',
    verified: true,
    listingType: 'For Sale',
    postedAgo: 'Saved 2d ago',
    title: 'BMW 220i M Sport Coupe',
    description:
      '2023 · 8,400 km · Auto · Petrol. Premium condition. PKR 89.5 Lakh.',
    imageUri: null,
    viewsLabel: '1.2k',
    likes: 248,
    liked: true,
    saved: true,
    category: 'Cars',
    city: 'Lahore',
    make: 'BMW',
    priceLakh: 89.5,
  },
  {
    id: 'saved-prius',
    sellerInitials: 'SC',
    sellerName: 'Supreme Cars',
    verified: true,
    listingType: 'For Sale',
    postedAgo: 'Saved 5d ago',
    title: 'Toyota Prius Hybrid',
    description: '2022 · 28,000 km · Hybrid. PKR 72 Lakh.',
    imageUri: null,
    viewsLabel: '860',
    likes: 132,
    liked: true,
    saved: true,
    category: 'Cars',
    city: 'Lahore',
    make: 'Toyota',
    priceLakh: 72,
  },
  {
    id: 'saved-merc',
    sellerInitials: 'AM',
    sellerName: 'Ali Motors',
    verified: true,
    listingType: 'For Rent',
    postedAgo: 'Saved 1w ago',
    title: 'Mercedes-Benz S 500',
    description: '2022 · 18,600 km · Luxury sedan. PKR 45,000/day.',
    imageUri: null,
    viewsLabel: '890',
    likes: 156,
    liked: true,
    saved: true,
    category: 'Cars',
    city: 'Lahore',
    make: 'Mercedes',
    priceLakh: null,
  },
];
