import {StyleSheet} from 'react-native';
import {type AppColors} from '../../../theme';

export const createStyles = (colors: AppColors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 40,
    gap: 14,
  },
  main: {
    width: '100%',
    maxWidth: 560,
    alignSelf: 'center',
    paddingHorizontal: 20,
    gap: 14,
  },
  pageHeader: {
    marginTop: 8,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  backBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.actionBlue,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
  },
  titleBlock: {
    flex: 1,
    gap: 2,
  },
  pageTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: colors.textDark,
    letterSpacing: -0.5,
    lineHeight: 28,
  },
  pageSubtitle: {
    fontSize: 12,
    fontWeight: '400',
    color: colors.textSoft,
    lineHeight: 16,
  },
  formCard: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    borderWidth: 0.75,
    borderColor: colors.borderSoft,
    padding: 16,
    gap: 14,
    shadowColor: '#0B152C',
    shadowOffset: {width: 0, height: 3},
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 1,
  },
  alertBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    padding: 12,
    borderRadius: 14,
    backgroundColor: '#FFF7ED',
    borderWidth: 1,
    borderColor: 'rgba(245,158,11,0.35)',
  },
  alertCopy: {
    flex: 1,
    gap: 2,
  },
  alertTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: '#C2410C',
  },
  alertBody: {
    fontSize: 11,
    fontWeight: '400',
    color: colors.textSoft,
    lineHeight: 15,
  },
  fieldsGrid: {
    gap: 12,
  },
  fieldRow: {
    flexDirection: 'row',
    gap: 10,
  },
  field: {
    flex: 1,
    gap: 6,
  },
  fieldFull: {
    gap: 6,
  },
  label: {
    fontSize: 9,
    fontWeight: '600',
    color: colors.textSoft,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  inputWrap: {
    height: 40,
    borderRadius: 12,
    borderWidth: 0.75,
    borderColor: colors.border,
    backgroundColor: colors.searchBg,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  input: {
    flex: 1,
    fontSize: 13,
    fontWeight: '500',
    color: colors.textDark,
    paddingVertical: 0,
  },
  textareaWrap: {
    minHeight: 88,
    borderRadius: 14,
    borderWidth: 0.75,
    borderColor: colors.border,
    backgroundColor: colors.searchBg,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  textarea: {
    fontSize: 13,
    fontWeight: '400',
    color: colors.textDark,
    textAlignVertical: 'top',
    minHeight: 68,
    paddingVertical: 0,
  },
  actionsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginTop: 2,
  },
  cancelBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    height: 36,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: colors.track,
  },
  cancelBtnText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textDark,
  },
  dangerTextBtn: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    height: 36,
  },
  dangerText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.error,
  },
  submitBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    height: 36,
    paddingHorizontal: 14,
    borderRadius: 12,
    backgroundColor: colors.actionBlue,
  },
  submitBtnText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.white,
  },
  slotsCard: {
    backgroundColor: colors.surface,
    borderRadius: 20,
    borderWidth: 0.75,
    borderColor: colors.borderSoft,
    padding: 16,
    gap: 12,
    shadowColor: '#0B152C',
    shadowOffset: {width: 0, height: 3},
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 1,
  },
  slotsLabel: {
    fontSize: 9,
    fontWeight: '600',
    color: colors.textSoft,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  slotsList: {
    gap: 8,
  },
  slotRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderRadius: 14,
    backgroundColor: colors.track,
  },
  slotLabel: {
    flex: 1,
    fontSize: 13,
    fontWeight: '600',
    color: colors.textDark,
  },
  useBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.actionBlue,
  },
});
