export const endpoints = {
  accountingBonuses: {
    listBonuses: '/bonuses',
    createBonuses: '/bonuses',
    getBonusesById: (bonus: string | number) => `/bonuses/${bonus}`,
    updateBonusesById: (bonus: string | number) => `/bonuses/${bonus}`,
    deleteBonusesById: (bonus: string | number) => `/bonuses/${bonus}`,
    approveBonusesById: (bonus: string | number) => `/bonuses/${bonus}/approve`,
  },
  accountingCustomers: {
    listCustomers: '/customers',
    createCustomers: '/customers',
    getCustomersById: (customer: string | number) => `/customers/${customer}`,
    updateCustomersById: (customer: string | number) => `/customers/${customer}`,
    deleteCustomersById: (customer: string | number) => `/customers/${customer}`,
  },
  accountingExpenseCategories: {
    listExpenseCategories: '/expense-categories',
    createExpenseCategories: '/expense-categories',
    getExpenseCategoriesById: (expenseCategory: string | number) => `/expense-categories/${expenseCategory}`,
    updateExpenseCategoriesById: (expenseCategory: string | number) => `/expense-categories/${expenseCategory}`,
    deleteExpenseCategoriesById: (expenseCategory: string | number) => `/expense-categories/${expenseCategory}`,
  },
  accountingExpenses: {
    listExpenses: '/expenses',
    createExpenses: '/expenses',
    getExpensesById: (expense: string | number) => `/expenses/${expense}`,
    updateExpensesById: (expense: string | number) => `/expenses/${expense}`,
    deleteExpensesById: (expense: string | number) => `/expenses/${expense}`,
    uploadReceipt: (expense: string | number) => `/expenses/${expense}/receipt`,
    approveExpensesById: (expense: string | number) => `/expenses/${expense}/approve`,
  },
  accountingLedger: {
    listLedger: '/ledger',
    getLedgerSummary: '/ledger/summary',
  },
  accountingPurchases: {
    listPurchases: '/purchases',
    createPurchases: '/purchases',
    getPurchasesById: (carPurchase: string | number) => `/purchases/${carPurchase}`,
    updatePurchasesById: (carPurchase: string | number) => `/purchases/${carPurchase}`,
    deletePurchasesById: (carPurchase: string | number) => `/purchases/${carPurchase}`,
  },
  accountingSales: {
    listSales: '/sales',
    createSales: '/sales',
    getSalesById: (carSale: string | number) => `/sales/${carSale}`,
    updateSalesById: (carSale: string | number) => `/sales/${carSale}`,
    deleteSalesById: (carSale: string | number) => `/sales/${carSale}`,
  },
  accountingSuppliers: {
    listSuppliers: '/suppliers',
    createSuppliers: '/suppliers',
    getSuppliersById: (supplier: string | number) => `/suppliers/${supplier}`,
    updateSuppliersById: (supplier: string | number) => `/suppliers/${supplier}`,
    deleteSuppliersById: (supplier: string | number) => `/suppliers/${supplier}`,
  },
  auditLogs: {
    listAuditLogs: '/audit-logs',
  },
  auth: {
    register: '/register',
    login: '/login',
    getMe: '/me',
    logout: '/logout',
  },
  dashboard: {
    getDashboard: '/dashboard',
  },
  jobsworkshop: {
    listJobs: '/jobs',
    createJobs: '/jobs',
    getJobsById: (job: string | number) => `/jobs/${job}`,
    updateJobsById: (job: string | number) => `/jobs/${job}`,
    deleteJobsById: (job: string | number) => `/jobs/${job}`,
  },
  notifications: {
    listNotifications: '/notifications',
    markRead: (notification: string | number) => `/notifications/${notification}/read`,
    markAllRead: '/notifications/read-all',
    deleteNotificationsById: (notification: string | number) => `/notifications/${notification}`,
  },
  publicSiteAuth: {
    register: '/public/auth/register',
    login: '/public/auth/login',
    loginWithGoogle: '/public/auth/google',
    getMe: '/public/auth/me',
    logout: '/public/auth/logout',
  },
  publicSiteEnquiries: {
    createPublicEnquiries: '/public/enquiries',
  },
  publicSiteFollow: {
    listPublicFollows: '/public/follows',
    createPublicFollows: '/public/follows',
    deletePublicFollowsById: (showroom: string | number) => `/public/follows/${showroom}`,
  },
  publicSiteSavedVehicles: {
    listPublicSavedVehicles: '/public/saved-vehicles',
    createPublicSavedVehicles: '/public/saved-vehicles',
    deletePublicSavedVehiclesById: (vehicle: string | number) => `/public/saved-vehicles/${vehicle}`,
  },
  publicSiteShowrooms: {
    listPublicShowrooms: '/public/showrooms',
    getPublicShowroomsById: (slug: string | number) => `/public/showrooms/${slug}`,
  },
  publicSiteVehicles: {
    listPublicVehicles: '/public/vehicles',
    getPublicVehiclesFilters: '/public/vehicles/filters',
    getPublicVehiclesById: (vehicle: string | number) => `/public/vehicles/${vehicle}`,
  },
  publicSiteJobs: {
    listPublicJobs: '/public/jobs',
    getPublicJobsFilters: '/public/jobs/filters',
    getPublicJobsById: (idOrSlug: string | number) => `/public/jobs/${idOrSlug}`,
    applyPublicJobsById: (idOrSlug: string | number) => `/public/jobs/${idOrSlug}/apply`,
  },
  rolesPermissions: {
    listRoles: '/roles',
    createRoles: '/roles',
    listPermissions: '/permissions',
    getRolesById: (role: string | number) => `/roles/${role}`,
    updateRolesById: (role: string | number) => `/roles/${role}`,
    deleteRolesById: (role: string | number) => `/roles/${role}`,
    assignShift: '/roles/assign',
  },
  settingsKeyvalueSettings: {
    listSettings: '/settings',
    createSettings: '/settings',
    deleteSettingsById: (setting: string | number) => `/settings/${setting}`,
  },
  settingsLanguages: {
    listLanguages: '/languages',
    createLanguages: '/languages',
    updateLanguagesById: (language: string | number) => `/languages/${language}`,
    deleteLanguagesById: (language: string | number) => `/languages/${language}`,
  },
  settingsPublicStorefront: {
    listShowroomProfilePublic: '/showroom-profile/public',
    updateShowroomProfilePublic: '/showroom-profile/public',
    uploadLogo: '/showroom-profile/public/logo',
    uploadCover: '/showroom-profile/public/cover',
  },
  settingsShowroomProfile: {
    listShowroomProfile: '/showroom-profile',
    updateShowroomProfile: '/showroom-profile',
    uploadLogo: '/showroom-profile/logo',
  },
  staffManagementAdvances: {
    listAdvances: '/advances',
    createAdvances: '/advances',
    getAdvancesById: (staffAdvance: string | number) => `/advances/${staffAdvance}`,
    updateAdvancesById: (staffAdvance: string | number) => `/advances/${staffAdvance}`,
    deleteAdvancesById: (staffAdvance: string | number) => `/advances/${staffAdvance}`,
  },
  staffManagementAttendance: {
    listAttendance: '/attendance',
    createAttendance: '/attendance',
    getAttendanceById: (staffAttendance: string | number) => `/attendance/${staffAttendance}`,
    updateAttendanceById: (staffAttendance: string | number) => `/attendance/${staffAttendance}`,
    deleteAttendanceById: (staffAttendance: string | number) => `/attendance/${staffAttendance}`,
  },
  staffManagementSalaries: {
    listSalaries: '/salaries',
    createSalaries: '/salaries',
    getSalariesById: (salary: string | number) => `/salaries/${salary}`,
    updateSalariesById: (salary: string | number) => `/salaries/${salary}`,
    deleteSalariesById: (salary: string | number) => `/salaries/${salary}`,
  },
  staffManagementShifts: {
    listShifts: '/shifts',
    createShifts: '/shifts',
    getShiftsById: (shift: string | number) => `/shifts/${shift}`,
    updateShiftsById: (shift: string | number) => `/shifts/${shift}`,
    deleteShiftsById: (shift: string | number) => `/shifts/${shift}`,
    assignShift: (shift: string | number) => `/shifts/${shift}/assign`,
  },
  staffManagementStaff: {
    listStaff: '/staff',
    createStaff: '/staff',
    getStaffById: (staff: string | number) => `/staff/${staff}`,
    updateStaffById: (staff: string | number) => `/staff/${staff}`,
    deleteStaffById: (staff: string | number) => `/staff/${staff}`,
    uploadPhoto: (staff: string | number) => `/staff/${staff}/photo`,
    uploadDocuments: (staff: string | number) => `/staff/${staff}/documents`,
  },
  superAdminPlatformDashboard: {
    listSuperAdminDashboard: '/super-admin/dashboard',
  },
  superAdminShowrooms: {
    listSuperAdminShowrooms: '/super-admin/showrooms',
    createSuperAdminShowrooms: '/super-admin/showrooms',
    getSuperAdminShowroomsById: (showroom: string | number) => `/super-admin/showrooms/${showroom}`,
    updateSuperAdminShowroomsById: (showroom: string | number) => `/super-admin/showrooms/${showroom}`,
    deleteSuperAdminShowroomsById: (showroom: string | number) => `/super-admin/showrooms/${showroom}`,
    setStatus: (showroom: string | number) => `/super-admin/showrooms/${showroom}/status`,
  },
  superAdminSubscriptionPlans: {
    listSuperAdminPlans: '/super-admin/plans',
    createSuperAdminPlans: '/super-admin/plans',
    getSuperAdminPlansById: (subscriptionPlan: string | number) => `/super-admin/plans/${subscriptionPlan}`,
    updateSuperAdminPlansById: (subscriptionPlan: string | number) => `/super-admin/plans/${subscriptionPlan}`,
    deleteSuperAdminPlansById: (subscriptionPlan: string | number) => `/super-admin/plans/${subscriptionPlan}`,
  },
  superAdminSubscriptions: {
    listSuperAdminSubscriptions: '/super-admin/subscriptions',
    createSuperAdminSubscriptions: '/super-admin/subscriptions',
    getSuperAdminSubscriptionsById: (subscription: string | number) => `/super-admin/subscriptions/${subscription}`,
    updateSuperAdminSubscriptionsById: (subscription: string | number) => `/super-admin/subscriptions/${subscription}`,
    deleteSuperAdminSubscriptionsById: (subscription: string | number) => `/super-admin/subscriptions/${subscription}`,
  },
  vehicleManagementCategories: {
    listCategories: '/categories',
    createCategories: '/categories',
    getCategoriesById: (carCategory: string | number) => `/categories/${carCategory}`,
    updateCategoriesById: (carCategory: string | number) => `/categories/${carCategory}`,
    deleteCategoriesById: (carCategory: string | number) => `/categories/${carCategory}`,
    uploadImage: (carCategory: string | number) => `/categories/${carCategory}/image`,
  },
  vehicleManagementMaintenance: {
    getVehiclesByIdMaintenance: (vehicle: string | number) => `/vehicles/${vehicle}/maintenance`,
    createVehiclesByIdMaintenance: (vehicle: string | number) => `/vehicles/${vehicle}/maintenance`,
  },
  vehicleManagementVehicles: {
    listVehicles: '/vehicles',
    createVehicles: '/vehicles',
    getVehiclesById: (vehicle: string | number) => `/vehicles/${vehicle}`,
    updateVehiclesById: (vehicle: string | number) => `/vehicles/${vehicle}`,
    deleteVehiclesById: (vehicle: string | number) => `/vehicles/${vehicle}`,
    uploadImages: (vehicle: string | number) => `/vehicles/${vehicle}/images`,
    deleteImage: (vehicle: string | number, image: string | number) => `/vehicles/${vehicle}/images/${image}`,
    uploadDocuments: (vehicle: string | number) => `/vehicles/${vehicle}/documents`,
    deleteDocument: (vehicle: string | number, document: string | number) => `/vehicles/${vehicle}/documents/${document}`,
  },
  vehicleRentalRentOrders: {
    listRentOrders: '/rent-orders',
    createRentOrders: '/rent-orders',
    getRentOrdersById: (rentOrder: string | number) => `/rent-orders/${rentOrder}`,
    updateRentOrdersById: (rentOrder: string | number) => `/rent-orders/${rentOrder}`,
    deleteRentOrdersById: (rentOrder: string | number) => `/rent-orders/${rentOrder}`,
  },
  vehicleRentalRentals: {
    listRentals: '/rentals',
    createRentals: '/rentals',
    getRentalsById: (rental: string | number) => `/rentals/${rental}`,
    updateRentalsById: (rental: string | number) => `/rentals/${rental}`,
    deleteRentalsById: (rental: string | number) => `/rentals/${rental}`,
    returnRental: (rental: string | number) => `/rentals/${rental}/return`,
  },
} as const;
