import {StyleSheet} from 'react-native';
import {type AppColors} from '../../../theme';
import {FEED_BG, FEED_BORDER, FEED_MUTED, FEED_PRIMARY} from './module';

export const createStyles = (_c: AppColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: FEED_BG,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingHorizontal: 16,
      paddingTop: 6,
      paddingBottom: 10,
      backgroundColor: '#fff',
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: FEED_BORDER,
    },
    avatarBtn: {
      width: 38,
      height: 38,
      borderRadius: 19,
      backgroundColor: '#dbeafe',
      alignItems: 'center',
      justifyContent: 'center',
    },
    searchBar: {
      flex: 1,
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: '#f3f4f6',
      borderRadius: 10,
      paddingHorizontal: 12,
      height: 38,
    },
    searchInput: {
      flex: 1,
      minWidth: 0,
      fontSize: 12,
      color: '#111827',
      paddingVertical: 0,
    },
    hdrActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    msgBtn: {
      width: 38,
      height: 38,
      borderRadius: 19,
      backgroundColor: '#f3f4f6',
      alignItems: 'center',
      justifyContent: 'center',
    },
    badge: {
      position: 'absolute',
      top: 6,
      right: 6,
      width: 8,
      height: 8,
      borderRadius: 4,
      backgroundColor: '#ef4444',
      borderWidth: 1.5,
      borderColor: '#fff',
    },
    filtersRow: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#fff',
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: FEED_BORDER,
      paddingVertical: 8,
      paddingLeft: 14,
      paddingRight: 10,
      gap: 8,
    },
    chipsScroll: {
      flexGrow: 0,
      flexShrink: 1,
    },
    chipsContent: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 7,
      paddingRight: 4,
    },
    fchip: {
      paddingHorizontal: 13,
      paddingVertical: 6,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: FEED_BORDER,
      backgroundColor: '#fff',
    },
    fchipOn: {
      backgroundColor: FEED_PRIMARY,
      borderColor: FEED_PRIMARY,
    },
    fchipText: {
      fontSize: 11,
      fontWeight: '500',
      color: FEED_MUTED,
    },
    fchipTextOn: {
      color: '#fff',
    },
    filterBtn: {
      width: 34,
      height: 34,
      borderRadius: 10,
      borderWidth: 1,
      borderColor: FEED_BORDER,
      backgroundColor: '#fff',
      alignItems: 'center',
      justifyContent: 'center',
    },
    filterBtnActive: {
      borderColor: FEED_PRIMARY,
      backgroundColor: '#eff6ff',
    },
    filterCount: {
      position: 'absolute',
      top: -4,
      right: -4,
      minWidth: 16,
      height: 16,
      paddingHorizontal: 4,
      borderRadius: 8,
      backgroundColor: FEED_PRIMARY,
      alignItems: 'center',
      justifyContent: 'center',
    },
    filterCountText: {
      fontSize: 9,
      fontWeight: '700',
      color: '#fff',
    },
    activeFiltersRow: {
      flexDirection: 'row',
      gap: 6,
      paddingHorizontal: 14,
      paddingTop: 8,
      paddingBottom: 2,
      backgroundColor: FEED_BG,
    },
    afilter: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingLeft: 10,
      paddingRight: 6,
      paddingVertical: 4,
      borderRadius: 14,
      backgroundColor: '#eff6ff',
      borderWidth: 1,
      borderColor: '#bfdbfe',
    },
    afilterText: {
      fontSize: 10,
      fontWeight: '600',
      color: FEED_PRIMARY,
    },
    afilterRemove: {
      paddingHorizontal: 2,
      paddingVertical: 1,
    },
    afilterRemoveText: {
      fontSize: 12,
      color: FEED_PRIMARY,
      lineHeight: 14,
    },
    listContent: {
      paddingHorizontal: 14,
      paddingTop: 10,
      paddingBottom: 24,
      gap: 12,
      flexGrow: 1,
    },
    empty: {
      paddingTop: 48,
      alignItems: 'center',
      gap: 6,
    },
    emptyTitle: {
      fontSize: 15,
      fontWeight: '700',
      color: '#111827',
    },
    emptySubtitle: {
      fontSize: 12,
      color: FEED_MUTED,
      textAlign: 'center',
      paddingHorizontal: 24,
    },
  });

export const createPostStyles = (_c: AppColors) =>
  StyleSheet.create({
    card: {
      backgroundColor: '#fff',
      borderRadius: 14,
      borderWidth: 1,
      borderColor: FEED_BORDER,
      overflow: 'hidden',
    },
    head: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 12,
      paddingTop: 11,
      paddingBottom: 8,
    },
    uploader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 9,
      flex: 1,
      minWidth: 0,
    },
    uploaderMeta: {
      flexShrink: 1,
      minWidth: 0,
    },
    avatar: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: '#dbeafe',
      alignItems: 'center',
      justifyContent: 'center',
    },
    avatarText: {
      fontSize: 11,
      fontWeight: '700',
      color: FEED_PRIMARY,
    },
    nameRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 3,
      flexShrink: 1,
    },
    name: {
      fontSize: 12,
      fontWeight: '700',
      color: '#111827',
      flexShrink: 1,
    },
    meta: {
      fontSize: 10,
      color: FEED_MUTED,
      marginTop: 1,
    },
    image: {
      width: '100%',
      backgroundColor: '#f3f4f6',
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
      overflow: 'hidden',
    },
    imageMedia: {
      width: '100%',
      height: '100%',
    },
    imagePlaceholder: {
      fontSize: 13,
      fontWeight: '600',
      color: FEED_MUTED,
      textAlign: 'center',
      paddingHorizontal: 16,
    },
    listingBadge: {
      position: 'absolute',
      top: 10,
      right: 10,
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 999,
      zIndex: 2,
    },
    listingBadgeSale: {
      backgroundColor: 'rgba(5, 150, 105, 0.95)',
    },
    listingBadgeRent: {
      backgroundColor: 'rgba(37, 99, 235, 0.95)',
    },
    listingBadgeText: {
      fontSize: 10,
      fontWeight: '700',
      letterSpacing: 0.2,
    },
    listingBadgeTextSale: {
      color: '#fff',
    },
    listingBadgeTextRent: {
      color: '#fff',
    },
    content: {
      paddingHorizontal: 12,
      paddingVertical: 10,
    },
    title: {
      fontSize: 14,
      fontWeight: '700',
      color: '#111827',
    },
    description: {
      fontSize: 11,
      color: FEED_MUTED,
      marginTop: 4,
      lineHeight: 15.4,
    },
    actions: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-around',
      paddingHorizontal: 12,
      paddingVertical: 9,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: FEED_BORDER,
    },
    action: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      paddingVertical: 2,
      paddingHorizontal: 4,
    },
    actionText: {
      fontSize: 11,
      color: FEED_MUTED,
    },
    actionLikeText: {
      color: '#ef4444',
    },
    actionSavedText: {
      color: FEED_PRIMARY,
    },
  });

export const createSheetStyles = (_c: AppColors) =>
  StyleSheet.create({
    backdrop: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: 'rgba(15,23,42,0.42)',
    },
    backdropTap: {
      ...StyleSheet.absoluteFill,
    },
    sheet: {
      backgroundColor: '#fff',
      borderTopLeftRadius: 22,
      borderTopRightRadius: 22,
      maxHeight: '78%',
      shadowColor: '#0F172A',
      shadowOffset: {width: 0, height: -8},
      shadowOpacity: 0.18,
      shadowRadius: 32,
      elevation: 12,
    },
    handle: {
      width: 36,
      height: 4,
      borderRadius: 2,
      backgroundColor: FEED_BORDER,
      alignSelf: 'center',
      marginTop: 10,
    },
    head: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: 10,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: FEED_BORDER,
    },
    headTitle: {
      fontSize: 15,
      fontWeight: '700',
      color: '#111827',
    },
    reset: {
      fontSize: 12,
      fontWeight: '600',
      color: FEED_PRIMARY,
    },
    body: {
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: 8,
    },
    block: {
      marginBottom: 16,
    },
    label: {
      fontSize: 11,
      fontWeight: '700',
      color: FEED_MUTED,
      textTransform: 'uppercase',
      letterSpacing: 0.4,
      marginBottom: 8,
    },
    chips: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 7,
    },
    chip: {
      paddingHorizontal: 12,
      paddingVertical: 7,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: FEED_BORDER,
      backgroundColor: '#fff',
    },
    chipOn: {
      backgroundColor: FEED_PRIMARY,
      borderColor: FEED_PRIMARY,
    },
    chipText: {
      fontSize: 11,
      fontWeight: '500',
      color: '#111827',
    },
    chipTextOn: {
      color: '#fff',
    },
    rangeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 8,
    },
    rangeInput: {
      flex: 1,
      height: 36,
      borderWidth: 1,
      borderColor: FEED_BORDER,
      borderRadius: 10,
      paddingHorizontal: 10,
      fontSize: 12,
      color: '#111827',
      backgroundColor: FEED_BG,
    },
    rangeTo: {
      fontSize: 11,
      color: FEED_MUTED,
    },
    foot: {
      flexDirection: 'row',
      gap: 8,
      paddingHorizontal: 16,
      paddingTop: 12,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: FEED_BORDER,
      backgroundColor: '#fff',
    },
    btn: {
      flex: 1,
      height: 42,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
    },
    btnGhost: {
      backgroundColor: '#f3f4f6',
    },
    btnPrimary: {
      backgroundColor: FEED_PRIMARY,
      shadowColor: FEED_PRIMARY,
      shadowOffset: {width: 0, height: 4},
      shadowOpacity: 0.3,
      shadowRadius: 12,
      elevation: 3,
    },
    btnGhostText: {
      fontSize: 13,
      fontWeight: '700',
      color: '#111827',
    },
    btnPrimaryText: {
      fontSize: 13,
      fontWeight: '700',
      color: '#fff',
    },
  });
