import type {FeedPost} from '../CustomerHome/module';

export const SHARED_POSTS: FeedPost[] = [
  {
    id: 'shared-merc',
    sellerInitials: 'AM',
    sellerName: 'Ali Motors',
    verified: true,
    listingType: 'For Rent',
    postedAgo: 'Shared 4h ago',
    title: 'Mercedes-Benz S 500',
    description: '2022 · 18,600 km · Luxury sedan. PKR 45,000/day.',
    imageUri: null,
    viewsLabel: '890',
    likes: 156,
    liked: true,
    saved: false,
    shared: true,
    category: 'Cars',
    city: 'Lahore',
    make: 'Mercedes',
    priceLakh: null,
  },
  {
    id: 'shared-prius',
    sellerInitials: 'SC',
    sellerName: 'Supreme Cars',
    verified: true,
    listingType: 'For Sale',
    postedAgo: 'Shared 2d ago',
    title: 'Toyota Prius Hybrid',
    description: '2022 · 28,000 km · Hybrid. PKR 72 Lakh.',
    imageUri: null,
    viewsLabel: '860',
    likes: 132,
    liked: true,
    saved: false,
    shared: true,
    category: 'Cars',
    city: 'Lahore',
    make: 'Toyota',
    priceLakh: 72,
  },
];
