import {StyleSheet} from 'react-native';
import {type AppColors} from '../../../theme';
import {FEED_BG, FEED_BORDER, FEED_MUTED, FEED_PRIMARY} from './module';

export const createStyles = (_c: AppColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: FEED_BG,
    },
    topbar: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingHorizontal: 14,
      paddingTop: 8,
      paddingBottom: 12,
      backgroundColor: '#fff',
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: FEED_BORDER,
    },
    backBtn: {
      width: 34,
      height: 34,
      borderRadius: 17,
      borderWidth: 1,
      borderColor: FEED_BORDER,
      backgroundColor: FEED_BG,
      alignItems: 'center',
      justifyContent: 'center',
    },
    title: {
      flex: 1,
      fontSize: 16,
      fontWeight: '700',
      color: '#111827',
    },
    saveBtn: {
      paddingHorizontal: 14,
      paddingVertical: 7,
      borderRadius: 9,
      backgroundColor: FEED_PRIMARY,
    },
    saveText: {
      fontSize: 12,
      fontWeight: '700',
      color: '#fff',
    },
    scroll: {
      flex: 1,
    },
    scrollContent: {
      paddingHorizontal: 16,
      paddingTop: 16,
      paddingBottom: 28,
    },
    photoBlock: {
      alignItems: 'center',
      marginBottom: 18,
    },
    photoWrap: {
      width: 88,
      height: 88,
      position: 'relative',
    },
    photo: {
      width: 88,
      height: 88,
      borderRadius: 44,
      backgroundColor: '#e5e7eb',
      borderWidth: 3,
      borderColor: '#fff',
    },
    photoPlaceholder: {
      alignItems: 'center',
      justifyContent: 'center',
    },
    photoPlaceholderText: {
      fontSize: 10,
      fontWeight: '600',
      color: FEED_MUTED,
      textAlign: 'center',
      paddingHorizontal: 8,
    },
    cameraBtn: {
      position: 'absolute',
      right: 0,
      bottom: 0,
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: FEED_PRIMARY,
      borderWidth: 2,
      borderColor: '#fff',
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: FEED_PRIMARY,
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.35,
      shadowRadius: 8,
      elevation: 3,
    },
    changePhoto: {
      marginTop: 8,
      fontSize: 12,
      fontWeight: '600',
      color: FEED_PRIMARY,
    },
    section: {
      marginBottom: 14,
    },
    sectionLabel: {
      fontSize: 11,
      fontWeight: '700',
      color: FEED_MUTED,
      textTransform: 'uppercase',
      letterSpacing: 0.4,
      marginBottom: 8,
      paddingLeft: 2,
    },
    card: {
      backgroundColor: '#fff',
      borderWidth: 1,
      borderColor: FEED_BORDER,
      borderRadius: 14,
      overflow: 'hidden',
      shadowColor: '#0F172A',
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.04,
      shadowRadius: 8,
      elevation: 1,
    },
    bgCard: {
      padding: 10,
    },
    bgPreview: {
      height: 100,
      borderRadius: 14,
      overflow: 'hidden',
      backgroundColor: '#e5e7eb',
    },
    bgPreviewImage: {
      width: '100%',
      height: '100%',
    },
    bgPreviewPlaceholder: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    bgPreviewPlaceholderText: {
      fontSize: 12,
      fontWeight: '600',
      color: FEED_MUTED,
    },
    bgChange: {
      position: 'absolute',
      right: 10,
      bottom: 10,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: 8,
      backgroundColor: 'rgba(255,255,255,0.95)',
      shadowColor: '#000',
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 2,
    },
    bgChangeText: {
      fontSize: 11,
      fontWeight: '700',
      color: '#111827',
    },
    thumbsRow: {
      flexDirection: 'row',
      gap: 8,
      marginTop: 10,
      paddingRight: 4,
    },
    thumb: {
      width: 64,
      height: 48,
      borderRadius: 8,
      overflow: 'hidden',
      borderWidth: 2,
      borderColor: 'transparent',
      backgroundColor: '#e5e7eb',
      opacity: 0.75,
    },
    thumbOn: {
      borderColor: FEED_PRIMARY,
      opacity: 1,
    },
    thumbImage: {
      width: '100%',
      height: '100%',
    },
    row: {
      flexDirection: 'row',
    },
    field: {
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: FEED_BORDER,
    },
    fieldHalf: {
      flex: 1,
    },
    fieldHalfLeft: {
      borderRightWidth: StyleSheet.hairlineWidth,
      borderRightColor: FEED_BORDER,
    },
    fieldLast: {
      borderBottomWidth: 0,
    },
    label: {
      fontSize: 10,
      fontWeight: '600',
      color: FEED_MUTED,
      marginBottom: 4,
    },
    input: {
      fontSize: 13,
      fontWeight: '500',
      color: '#111827',
      padding: 0,
      margin: 0,
    },
    textarea: {
      minHeight: 56,
      textAlignVertical: 'top',
      lineHeight: 18,
    },
    locBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginTop: 8,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderRadius: 10,
      borderWidth: 1,
      borderStyle: 'dashed',
      borderColor: '#93c5fd',
      backgroundColor: '#eff6ff',
    },
    locBtnText: {
      fontSize: 12,
      fontWeight: '600',
      color: FEED_PRIMARY,
    },
  });
