import {StyleSheet} from 'react-native';
import {type AppColors} from '../../../theme';

export const createStyles = (colors: AppColors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 40,
    gap: 16,
  },
  main: {
    width: '100%',
    maxWidth: 560,
    alignSelf: 'center',
    paddingHorizontal: 20,
    gap: 14,
  },
  pageHeader: {
    marginTop: 8,
    gap: 3,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.actionBlue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pageTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.textDark,
    letterSpacing: -0.68,
    lineHeight: 30,
  },
  pageSubtitle: {
    fontSize: 12,
    fontWeight: '400',
    color: colors.textSoft,
    lineHeight: 18,
  },
  companyHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  companyIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.actionBlue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  companyCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  companyTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textDark,
  },
  companySubtitle: {
    fontSize: 11,
    color: colors.textSoft,
    lineHeight: 15,
  },
  saveBtn: {
    height: 34,
    borderRadius: 17,
    backgroundColor: colors.actionBlue,
    paddingHorizontal: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.white,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 24,
    borderWidth: 0.75,
    borderColor: colors.borderSoft,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 16,
    gap: 14,
    shadowColor: '#0B152C',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 2,
  },
  sectionEyebrow: {
    fontSize: 10,
    fontWeight: '600',
    color: colors.textSoft,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: colors.textDark,
    letterSpacing: -0.3,
  },
  sectionHeader: {
    gap: 2,
  },
  uploadBox: {
    borderWidth: 1.5,
    borderStyle: 'dashed',
    borderColor: '#D5DEE8',
    borderRadius: 18,
    backgroundColor: '#F8FAFC',
    minHeight: 120,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 24,
    paddingHorizontal: 16,
    gap: 8,
    overflow: 'hidden',
  },
  logoPreview: {
    width: 72,
    height: 72,
    borderRadius: 12,
  },
  uploadIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  uploadTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.textDark,
  },
  uploadHint: {
    fontSize: 11,
    color: colors.textSoft,
  },
  colorRow: {
    flexDirection: 'row',
    gap: 10,
  },
  colorSwatch: {
    flex: 1,
    height: 40,
    borderRadius: 20,
    borderWidth: 2.5,
    borderColor: 'transparent',
  },
  colorSwatchSelected: {
    borderColor: colors.textDark,
  },
  fieldsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  field: {
    width: '100%',
    gap: 6,
  },
  fieldHalf: {
    width: '47.5%',
    flexGrow: 1,
  },
  fieldLabel: {
    fontSize: 11,
    fontWeight: '500',
    color: colors.textSoft,
  },
  fieldInput: {
    height: 40,
    borderRadius: 12,
    borderWidth: 0.75,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    paddingHorizontal: 12,
    fontSize: 13,
    color: colors.textDark,
  },
  fieldInputFocused: {
    borderColor: colors.actionBlue,
    borderWidth: 1.25,
  },
});
