import type {FeedPost} from '../CustomerHome/module';

export const LIKED_POSTS: FeedPost[] = [
  {
    id: 'liked-civic',
    sellerInitials: 'CC',
    sellerName: 'City Cars',
    verified: false,
    listingType: 'For Sale',
    postedAgo: 'Liked 1d ago',
    title: 'Honda Civic RS Turbo',
    description: '2024 · 3,200 km · Single owner. PKR 78 Lakh.',
    imageUri: null,
    viewsLabel: '2.1k',
    likes: 412,
    liked: true,
    saved: false,
    category: 'Cars',
    city: 'Lahore',
    make: 'Honda',
    priceLakh: 78,
  },
  {
    id: 'liked-bmw',
    sellerInitials: 'AW',
    sellerName: 'Auto World',
    verified: true,
    listingType: 'For Sale',
    postedAgo: 'Liked 3d ago',
    title: 'BMW 220i M Sport Coupe',
    description:
      '2023 · 8,400 km · Auto · Petrol. Premium condition. PKR 89.5 Lakh.',
    imageUri: null,
    viewsLabel: '1.2k',
    likes: 248,
    liked: true,
    saved: false,
    category: 'Cars',
    city: 'Lahore',
    make: 'BMW',
    priceLakh: 89.5,
  },
  {
    id: 'liked-city',
    sellerInitials: 'SC',
    sellerName: 'Supreme Cars',
    verified: true,
    listingType: 'For Rent',
    postedAgo: 'Liked 6d ago',
    title: 'Honda City Aspire',
    description: '2023 · 12,400 km · For rent. PKR 8.5k/day.',
    imageUri: null,
    viewsLabel: '640',
    likes: 98,
    liked: true,
    saved: false,
    category: 'Cars',
    city: 'Lahore',
    make: 'Honda',
    priceLakh: null,
  },
];
