import {StyleSheet} from 'react-native';
import {type AppColors} from '../../../theme';

export const createStyles = (colors: AppColors) =>
  StyleSheet.create({
    container: {flex: 1, backgroundColor: colors.background},
    scroll: {flex: 1},
    scrollContent: {paddingBottom: 40},
    main: {paddingHorizontal: 20, gap: 14, paddingTop: 8},
    titleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    backBtn: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: colors.actionBlue,
      alignItems: 'center',
      justifyContent: 'center',
    },
    pageTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: colors.textDark,
      letterSpacing: -0.4,
    },
    heroCard: {
      backgroundColor: colors.surface,
      borderRadius: 24,
      borderWidth: 0.75,
      borderColor: colors.borderSoft,
      padding: 16,
      gap: 12,
      shadowColor: '#0F172A',
      shadowOffset: {width: 0, height: 4},
      shadowOpacity: 0.08,
      shadowRadius: 12,
      elevation: 3,
    },
    statusBadge: {
      alignSelf: 'flex-start',
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 999,
    },
    statusText: {fontSize: 9, fontWeight: '700'},
    makeYear: {fontSize: 10, color: colors.textSoft, fontWeight: '500'},
    heroTitle: {
      fontSize: 20,
      fontWeight: '700',
      color: colors.textDark,
      letterSpacing: -0.5,
    },
    heroDescription: {
      fontSize: 10,
      color: colors.textSoft,
      lineHeight: 15,
    },
    priceRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    priceValue: {
      fontSize: 18,
      fontWeight: '700',
      color: colors.actionBlue,
    },
    priceSuffix: {fontSize: 11, fontWeight: '500', color: colors.textSoft},
    ratingRow: {flexDirection: 'row', alignItems: 'center', gap: 4},
    ratingText: {fontSize: 10, fontWeight: '600', color: colors.textDark},
    actionRow: {flexDirection: 'row', gap: 8},
    rentBtn: {
      flex: 1,
      height: 34,
      borderRadius: 18,
      backgroundColor: colors.actionBlue,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
    },
    rentBtnText: {fontSize: 11, fontWeight: '600', color: colors.white},
    editBtn: {
      height: 34,
      paddingHorizontal: 14,
      borderRadius: 18,
      borderWidth: 0.75,
      borderColor: colors.borderSoft,
      backgroundColor: colors.surface,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    editBtnText: {fontSize: 11, fontWeight: '500', color: colors.textDark},
    imageWrap: {
      height: 150,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      padding: 10,
    },
    image: {width: '100%', height: '100%'},
    tabWrap: {
      borderRadius: 16,
      backgroundColor: colors.track,
      borderWidth: 0.75,
      borderColor: colors.borderSoft,
      padding: 4,
    },
    tabContent: {gap: 4},
    tab: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 12,
    },
    tabActive: {backgroundColor: colors.actionBlue},
    tabLabel: {fontSize: 10, fontWeight: '600', color: colors.textSoft},
    tabLabelActive: {color: colors.white},
    panel: {
      backgroundColor: colors.surface,
      borderRadius: 20,
      borderWidth: 0.75,
      borderColor: colors.borderSoft,
      padding: 14,
      gap: 12,
    },
    panelHeader: {gap: 3},
    panelEyebrow: {
      fontSize: 9,
      fontWeight: '700',
      color: colors.textSoft,
      letterSpacing: 0.4,
      textTransform: 'uppercase',
    },
    panelTitle: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.textDark,
    },
    panelSubtitle: {fontSize: 10, color: colors.textSoft},
    panelActions: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
    },
    primaryChipBtn: {
      height: 28,
      paddingHorizontal: 12,
      borderRadius: 18,
      backgroundColor: colors.actionBlue,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
    },
    primaryChipText: {fontSize: 10, fontWeight: '600', color: colors.white},
    specGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    specCell: {
      width: '31%',
      flexGrow: 1,
      minWidth: '30%',
      borderRadius: 12,
      backgroundColor: 'rgba(237,242,248,0.7)',
      borderWidth: 0.75,
      borderColor: colors.borderSoft,
      padding: 10,
      gap: 3,
    },
    specLabel: {
      fontSize: 8,
      fontWeight: '700',
      color: colors.textSoft,
      textTransform: 'uppercase',
    },
    specValue: {fontSize: 10, fontWeight: '600', color: colors.textDark},
    pillsRow: {flexDirection: 'row', flexWrap: 'wrap', gap: 6},
    pill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: 8,
      paddingVertical: 5,
      borderRadius: 999,
      backgroundColor: colors.actionTint06,
      borderWidth: 0.75,
      borderColor: colors.actionTint15,
    },
    pillText: {fontSize: 8.5, fontWeight: '600', color: colors.textDark},
    statsList: {gap: 8},
    statCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      padding: 14,
      borderRadius: 18,
      backgroundColor: colors.surface,
      borderWidth: 0.75,
      borderColor: colors.borderSoft,
    },
    statIconWrap: {
      width: 38,
      height: 38,
      borderRadius: 19,
      alignItems: 'center',
      justifyContent: 'center',
    },
    statCopy: {flex: 1, gap: 2},
    statLabel: {
      fontSize: 8.5,
      fontWeight: '700',
      color: colors.textSoft,
      letterSpacing: 0.4,
    },
    statValue: {
      fontSize: 18,
      fontWeight: '700',
      color: colors.textDark,
      letterSpacing: -0.4,
    },
    activityCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      padding: 12,
      borderRadius: 16,
      backgroundColor: colors.surface,
      borderWidth: 0.75,
      borderColor: colors.borderSoft,
      marginBottom: 8,
    },
    activityIconWrap: {
      width: 34,
      height: 34,
      borderRadius: 17,
      alignItems: 'center',
      justifyContent: 'center',
    },
    activityCopy: {flex: 1, gap: 3},
    activityTitle: {
      fontSize: 11,
      fontWeight: '600',
      color: colors.textDark,
      lineHeight: 15,
    },
    activityTime: {
      fontSize: 9.5,
      color: colors.textSoft,
    },
    statGrid: {flexDirection: 'row', flexWrap: 'wrap', gap: 8},
    summaryRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      paddingVertical: 6,
      borderBottomWidth: 0.75,
      borderBottomColor: colors.borderSoft,
    },
    summaryLabel: {fontSize: 10, color: colors.textSoft},
    summaryValue: {fontSize: 10, fontWeight: '600', color: colors.textDark},
    summaryValueDanger: {fontSize: 10, fontWeight: '700', color: colors.error},
    tableHeader: {
      flexDirection: 'row',
      paddingVertical: 8,
      borderBottomWidth: 1,
      borderBottomColor: colors.borderSoft,
    },
    tableHeaderText: {
      flex: 1,
      fontSize: 8,
      fontWeight: '700',
      color: colors.textSoft,
      textTransform: 'uppercase',
    },
    tableRow: {
      flexDirection: 'row',
      paddingVertical: 10,
      borderBottomWidth: 0.75,
      borderBottomColor: colors.borderSoft,
      alignItems: 'center',
    },
    tableCell: {flex: 1, fontSize: 9.5, color: colors.textDark},
    statusPill: {
      alignSelf: 'flex-start',
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 999,
      backgroundColor: colors.badgeActiveBg,
    },
    statusPillText: {
      fontSize: 8,
      fontWeight: '700',
      color: colors.successBright,
    },
    docCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      padding: 12,
      borderRadius: 14,
      borderWidth: 0.75,
      borderColor: colors.borderSoft,
      backgroundColor: colors.surface,
    },
    docCopy: {flex: 1, gap: 3},
    docTitle: {fontSize: 11, fontWeight: '700', color: colors.textDark},
    docMeta: {fontSize: 9, color: colors.textSoft},
    insuranceCard: {
      borderRadius: 16,
      borderWidth: 0.75,
      borderColor: colors.borderSoft,
      backgroundColor: colors.actionTint06,
      padding: 14,
      gap: 10,
    },
    claimCard: {
      borderRadius: 14,
      borderWidth: 0.75,
      borderColor: colors.borderSoft,
      padding: 12,
      gap: 6,
    },
    serviceCard: {
      borderRadius: 14,
      borderWidth: 0.75,
      borderColor: colors.borderSoft,
      padding: 12,
      gap: 4,
    },
    serviceTop: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 8,
    },
    serviceTitle: {fontSize: 11, fontWeight: '700', color: colors.textDark},
    serviceCost: {fontSize: 11, fontWeight: '700', color: colors.actionBlue},
    serviceDetails: {fontSize: 9.5, color: colors.textSoft},
    photoAdd: {
      height: 120,
      borderRadius: 16,
      borderWidth: 1.5,
      borderStyle: 'dashed',
      borderColor: colors.actionBlue,
      backgroundColor: colors.actionTint04,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
    },
    photoAddText: {fontSize: 11, fontWeight: '600', color: colors.actionBlue},
    photoCard: {
      height: 110,
      borderRadius: 16,
      backgroundColor: colors.searchBg,
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
    },
    legendRow: {flexDirection: 'row', flexWrap: 'wrap', gap: 10},
    legendItem: {flexDirection: 'row', alignItems: 'center', gap: 5},
    legendDot: {width: 8, height: 8, borderRadius: 4},
    legendText: {fontSize: 9, color: colors.textSoft},
    calendarGrid: {flexDirection: 'row', flexWrap: 'wrap', gap: 6},
    calendarDot: {width: 14, height: 14, borderRadius: 7},
    compactStatCard: {
      width: '31.5%',
      flexGrow: 1,
      minWidth: '30%',
      borderRadius: 14,
      backgroundColor: 'rgba(237,242,248,0.7)',
      borderWidth: 0.75,
      borderColor: colors.borderSoft,
      paddingHorizontal: 10,
      paddingVertical: 12,
      gap: 6,
    },
    compactStatIcon: {
      width: 28,
      height: 28,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
    },
    compactStatLabel: {
      fontSize: 7.5,
      fontWeight: '700',
      color: colors.textSoft,
      letterSpacing: 0.3,
    },
    compactStatValue: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.textDark,
      letterSpacing: -0.2,
    },
    maintenanceScroll: {
      maxHeight: 360,
    },
    maintenanceScrollContent: {
      gap: 10,
      paddingBottom: 4,
    },
    maintenanceCard: {
      borderRadius: 16,
      borderWidth: 0.75,
      borderColor: colors.borderSoft,
      backgroundColor: colors.surface,
      paddingHorizontal: 14,
      paddingVertical: 12,
      gap: 12,
    },
    maintenanceCardTop: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 10,
    },
    maintenanceCardCopy: {flex: 1, gap: 3},
    maintenanceType: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.textDark,
    },
    maintenanceDate: {
      fontSize: 10,
      color: colors.textSoft,
    },
    maintenanceMetaRow: {
      flexDirection: 'row',
      gap: 8,
    },
    maintenanceMetaItem: {
      flex: 1,
      gap: 2,
    },
    maintenanceMetaLabel: {
      fontSize: 8,
      fontWeight: '700',
      color: colors.textSoft,
      textTransform: 'uppercase',
      letterSpacing: 0.3,
    },
    maintenanceMetaValue: {
      fontSize: 10,
      fontWeight: '600',
      color: colors.textDark,
    },
    maintenanceCost: {
      fontSize: 11,
      fontWeight: '700',
      color: colors.actionBlue,
    },
    rentalHistoryCard: {
      borderRadius: 14,
      borderWidth: 0.75,
      borderColor: colors.borderSoft,
      backgroundColor: colors.surface,
      paddingHorizontal: 14,
      paddingVertical: 12,
      gap: 6,
    },
    rentalCustomer: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.textDark,
    },
    rentalHistoryMeta: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 8,
    },
    rentalHistoryMetaText: {
      flex: 1,
      fontSize: 10,
      color: colors.textSoft,
    },
    rentalDays: {
      fontSize: 10,
      fontWeight: '700',
      color: colors.actionBlue,
    },
  });
