import {StyleSheet} from 'react-native';
import {type AppColors} from '../../theme';

export const createStyles = (colors: AppColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.white,
    },
    scroll: {
      flex: 1,
    },
    scrollContent: {
      flexGrow: 1,
      paddingHorizontal: 24,
      paddingTop: 20,
      paddingBottom: 32,
    },
    brandRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      marginBottom: 24,
    },
    brandBadge: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: colors.brandBlue,
      alignItems: 'center',
      justifyContent: 'center',
    },
    brandBadgeText: {
      fontSize: 16,
      fontWeight: '800',
      color: colors.white,
    },
    brandName: {
      fontSize: 20,
      fontWeight: '800',
      color: colors.textDark,
      letterSpacing: -0.3,
    },
    title: {
      fontSize: 28,
      lineHeight: 34,
      fontWeight: '800',
      color: colors.textDark,
      letterSpacing: -0.5,
      marginBottom: 8,
    },
    subtitle: {
      fontSize: 14,
      lineHeight: 20,
      color: colors.textSoft,
      marginBottom: 18,
    },
    roleRow: {
      flexDirection: 'row',
      gap: 10,
      marginBottom: 18,
    },
    roleCard: {
      flex: 1,
      minHeight: 78,
      borderRadius: 16,
      borderWidth: 1.5,
      borderColor: colors.border,
      backgroundColor: colors.white,
      paddingHorizontal: 12,
      paddingVertical: 12,
      justifyContent: 'center',
      gap: 4,
    },
    roleCardSelected: {
      borderColor: colors.brandBlue,
      backgroundColor: '#EAF3FF',
    },
    roleTitle: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.textDark,
    },
    roleDescription: {
      fontSize: 11,
      lineHeight: 15,
      color: colors.textSoft,
    },
    socialBtn: {
      height: 48,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.white,
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 10,
    },
    socialBtnText: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.textDark,
    },
    orRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginTop: 8,
      marginBottom: 18,
    },
    orLine: {
      flex: 1,
      height: StyleSheet.hairlineWidth,
      backgroundColor: colors.border,
    },
    orText: {
      fontSize: 12,
      fontWeight: '600',
      color: colors.textSoft,
      letterSpacing: 0.6,
    },
    form: {
      gap: 14,
    },
    field: {
      gap: 8,
    },
    label: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.textDark,
    },
    required: {
      color: '#EF4444',
      fontWeight: '700',
    },
    optional: {
      color: colors.textSoft,
      fontWeight: '500',
    },
    input: {
      height: 48,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      paddingHorizontal: 16,
      fontSize: 14,
      color: colors.text,
      backgroundColor: colors.white,
    },
    textarea: {
      height: 88,
      paddingTop: 12,
      paddingBottom: 12,
    },
    phoneRow: {
      flexDirection: 'row',
      gap: 8,
      alignItems: 'center',
    },
    dialCode: {
      height: 48,
      minWidth: 88,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      paddingHorizontal: 10,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      backgroundColor: colors.white,
    },
    dialFlag: {
      fontSize: 16,
    },
    dialText: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.textDark,
    },
    phoneInput: {
      flex: 1,
    },
    select: {
      height: 48,
      borderWidth: 1,
      borderColor: colors.border,
      borderRadius: 14,
      paddingHorizontal: 16,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: colors.white,
    },
    selectDisabled: {
      opacity: 0.55,
    },
    selectPlaceholder: {
      fontSize: 14,
      color: colors.textSoft,
    },
    selectValue: {
      fontSize: 14,
      color: colors.text,
      fontWeight: '500',
    },
    chev: {
      fontSize: 14,
      color: colors.textSoft,
    },
    uploadBox: {
      minHeight: 88,
      borderWidth: 1.5,
      borderStyle: 'dashed',
      borderColor: '#93c5fd',
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      padding: 14,
      backgroundColor: '#F8FBFF',
      gap: 4,
    },
    uploadTitle: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.brandBlue,
    },
    uploadHint: {
      fontSize: 11,
      color: colors.textSoft,
    },
    logoPreviewRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      width: '100%',
    },
    logoThumb: {
      width: 48,
      height: 48,
      borderRadius: 10,
      backgroundColor: '#e5e7eb',
    },
    clearLogo: {
      marginTop: 4,
      fontSize: 12,
      fontWeight: '600',
      color: '#EF4444',
    },
    modalScrim: {
      flex: 1,
      backgroundColor: 'rgba(15,23,42,0.45)',
      justifyContent: 'center',
      padding: 24,
    },
    modalCard: {
      backgroundColor: colors.white,
      borderRadius: 16,
      paddingVertical: 12,
      maxHeight: '70%',
    },
    modalTitle: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.textDark,
      paddingHorizontal: 16,
      paddingBottom: 8,
    },
    modalItem: {
      paddingHorizontal: 16,
      paddingVertical: 14,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.border,
    },
    modalItemText: {
      fontSize: 14,
      color: colors.textDark,
      fontWeight: '500',
    },
    inputError: {
      borderColor: '#EF4444',
    },
    errorText: {
      fontSize: 12,
      fontWeight: '500',
      color: '#EF4444',
    },
    passwordWrap: {
      position: 'relative',
      justifyContent: 'center',
    },
    passwordInput: {
      paddingRight: 48,
    },
    eyeBtn: {
      position: 'absolute',
      right: 14,
      width: 28,
      height: 28,
      alignItems: 'center',
      justifyContent: 'center',
    },
    termsRow: {
      marginTop: 16,
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
    },
    checkbox: {
      width: 18,
      height: 18,
      borderRadius: 9,
      borderWidth: 1.5,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 1,
    },
    checkboxChecked: {
      borderColor: colors.brandBlue,
      backgroundColor: colors.brandBlue,
    },
    checkboxDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: colors.white,
    },
    termsText: {
      flex: 1,
      fontSize: 13,
      lineHeight: 18,
      color: colors.textSoft,
    },
    primaryBtn: {
      marginTop: 18,
      height: 52,
      borderRadius: 999,
      backgroundColor: colors.brandBlue,
      alignItems: 'center',
      justifyContent: 'center',
    },
    primaryBtnDisabled: {
      opacity: 0.7,
    },
    primaryBtnText: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.white,
    },
    switchRow: {
      marginTop: 18,
      flexDirection: 'row',
      justifyContent: 'center',
      alignItems: 'center',
      flexWrap: 'wrap',
    },
    switchText: {
      fontSize: 13,
      color: colors.textSoft,
    },
    switchLink: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.brandBlue,
    },
  });
