import {StyleSheet} from 'react-native';
import {type AppColors} from '../../../theme';

export const createStyles = (colors: AppColors) => StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 40,
    gap: 16,
  },
  main: {
    width: '100%',
    maxWidth: 560,
    alignSelf: 'center',
    paddingHorizontal: 20,
    gap: 14,
  },
  pageHeader: {
    marginTop: 8,
    gap: 3,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  backBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.actionBlue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pageTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.textDark,
    letterSpacing: -0.68,
    lineHeight: 30,
  },
  pageSubtitle: {
    fontSize: 12,
    fontWeight: '400',
    color: colors.textSoft,
    lineHeight: 18,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  sectionIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.actionBlue,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionCopy: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textDark,
  },
  sectionSubtitle: {
    fontSize: 11,
    color: colors.textSoft,
    lineHeight: 15,
  },
  saveBtn: {
    height: 34,
    borderRadius: 17,
    backgroundColor: colors.actionBlue,
    paddingHorizontal: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveBtnText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.white,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 24,
    borderWidth: 0.75,
    borderColor: colors.borderSoft,
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 6,
    shadowColor: '#0B152C',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 2,
  },
  cardHeader: {
    gap: 2,
    marginBottom: 10,
  },
  cardEyebrow: {
    fontSize: 10,
    fontWeight: '600',
    color: colors.textSoft,
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  cardTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: colors.textDark,
    letterSpacing: -0.3,
  },
  columnHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingBottom: 8,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  eventColHeader: {
    flex: 1,
    fontSize: 10,
    fontWeight: '600',
    color: colors.textSoft,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  toggleColHeader: {
    width: 52,
    textAlign: 'center',
    fontSize: 10,
    fontWeight: '600',
    color: colors.textSoft,
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
    gap: 4,
  },
  rowLast: {
    borderBottomWidth: 0,
  },
  eventCopy: {
    flex: 1,
    minWidth: 0,
    paddingRight: 8,
    gap: 2,
  },
  eventTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textDark,
  },
  eventSubtitle: {
    fontSize: 11,
    color: colors.textSoft,
    lineHeight: 15,
  },
  toggleCol: {
    width: 52,
    alignItems: 'center',
    justifyContent: 'center',
  },
  toggle: {
    transform: [{scaleX: 0.78}, {scaleY: 0.78}],
  },
});
